--------------------------------------------------------
--  DDL for Function GET_REP_MAN_ENTRY
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "GET_REP_MAN_ENTRY" 
(
  P_S_HEAT_ID IN NUMBER
, P_FIELD_NAME IN VARCHAR2
, P_UNIT IN VARCHAR2
, P_UNIT_NO IN NUMBER
) RETURN VARCHAR2 AS

pResult varchar2(256);
BEGIN

  pResult := '';
  IF(P_UNIT='EAF') THEN
    SELECT FIELD_VALUE into pResult FROM pe_heat_rep_man WHERE FIELD_NAME=P_FIELD_NAME AND S_HEAT_ID=P_S_HEAT_ID AND CREATED=(SELECT MAX(CREATED) FROM pe_heat_rep_man WHERE FIELD_NAME=P_FIELD_NAME AND S_HEAT_ID=P_S_HEAT_ID);
  END IF;
  IF(P_UNIT='LF') THEN
    SELECT FIELD_VALUE into pResult FROM pl_heat_rep_man WHERE FIELD_NAME=P_FIELD_NAME AND S_HEAT_ID=P_S_HEAT_ID AND CREATED=(SELECT MAX(CREATED) FROM pl_heat_rep_man WHERE FIELD_NAME=P_FIELD_NAME AND S_HEAT_ID=P_S_HEAT_ID);
  END IF;

  IF(P_UNIT='VD') THEN
    SELECT FIELD_VALUE into pResult FROM pv_heat_rep_man WHERE FIELD_NAME=P_FIELD_NAME AND S_HEAT_ID=P_S_HEAT_ID AND CREATED=(SELECT MAX(CREATED) FROM pv_heat_rep_man WHERE FIELD_NAME=P_FIELD_NAME AND S_HEAT_ID=P_S_HEAT_ID);
  END IF;

  IF(P_UNIT='BC') THEN
    SELECT FIELD_VALUE into pResult FROM pc_heat_rep_man WHERE FIELD_NAME=P_FIELD_NAME AND S_HEAT_ID=P_S_HEAT_ID AND CREATED=(SELECT MAX(CREATED) FROM pc_heat_rep_man WHERE FIELD_NAME=P_FIELD_NAME AND S_HEAT_ID=P_S_HEAT_ID);
  END IF;

  RETURN pResult;
  EXCEPTION WHEN OTHERS THEN RETURN '';

END GET_REP_MAN_ENTRY;

/
