--------------------------------------------------------
--  DDL for Function GET_REP_EQ_LIFE
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "GET_REP_EQ_LIFE" 
(
  P_EQ_NAME_PARENT IN VARCHAR2
, P_EQ_NAME IN VARCHAR2
, P_COUNTER_NAME IN VARCHAR2
) RETURN NUMBER AS

pResult NUMBER;
BEGIN

  pResult := 0;
  SELECT EQUIPMENT_LIFE_VALUE into pResult from P_EQUIPMENT_LIFE WHERE C_EQUIPMENT_COUNTER_ID=(SELECT ID FROM C_EQUIPMENT_COUNTER WHERE COUNTER_NAME=P_COUNTER_NAME) AND
  C_EQUIPMENT_ID=(SELECT ID FROM C_EQUIPMENT ce WHERE P_EQ_NAME_PARENT || P_EQ_NAME = ce.EQUIPMENT_NAME);
  RETURN pResult;
  EXCEPTION WHEN OTHERS THEN RETURN 0;
return pResult;
END GET_REP_EQ_LIFE;

/
