--------------------------------------------------------
--  DDL for View V_L2_DEV_REQ
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_L2_DEV_REQ" ("ID", "TARGET_DIALOG", "REQUEST_DESCRIPTION", "C_HMI_DIALOG_ID") AS 
  SELECT
CHDR.ID AS ID,
CHDR.TARGET_DIALOG AS TARGET_DIALOG,
CHDR.REQUEST_DESCRIPTION AS REQUEST_DESCRIPTION,
CHDR.C_HMI_DIALOG_ID AS C_HMI_DIALOG_ID
FROM C_HMI_DEV_REQ CHDR, C_HMI_DIALOG CHD
WHERE CHD.ID = CHDR.C_HMI_DIALOG_ID;
