--------------------------------------------------------
--  DDL for View V_LF_PRACTICE2
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_LF_PRACTICE2" ("CLPE_ID", "CLEP_ID", "STEP_SEQ_NO", "DUR", "VOLTAGE_TAP", "TRANSFORMER_CURVE", "ELECTRIC_POWER", "IS_VARIABLE_STEP", "CL_PRACTICE_PHASE_ID") AS 
  SELECT
CLPE.ID AS CLPE_ID,
CLEP.ID AS CLEP_ID,
CLPE.STEP_SEQ_NO AS STEP_SEQ_NO,
CLPE.DURATION AS DUR,
CLEP.VOLTAGE_TAP AS VOLTAGE_TAP,
0 AS TRANSFORMER_CURVE,
CLEP.ELECTRIC_POWER,
CLPE.STEP_TYPE AS IS_VARIABLE_STEP,
CLPE.CL_PRACTICE_PHASE_ID AS CL_PRACTICE_PHASE_ID
FROM CL_EL_POWER CLEP, CL_PRACT_ELECTRIC CLPE
WHERE CLPE.CL_EL_POWER_ID(+)=CLEP.ID
ORDER BY STEP_SEQ_NO;
