--------------------------------------------------------
--  DDL for View V_LF_PRACTICE3
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_LF_PRACTICE3" ("CB_ID", "CMTD_ID", "C_MATERIAL_TAB_ID", "MAT_CODE", "BUNKER_NO", "MAT_AMOUNT", "RELATIVE_ADD", "PERCENT_ADD", "MULTIPLE_ADD", "ABSOLUTE_ADD") AS 
  SELECT
  cb.ID as CB_ID,
  cmtd.ID as CMTD_ID,
  cmtd.c_material_tab_id AS c_material_tab_id,
CM.MAT_CODE AS MAT_CODE,
CB.BUNKER_NO AS BUNKER_NO,
CB.MAT_AMOUNT AS MAT_AMOUNT,
CMTD.RELATIVE_ADD AS RELATIVE_ADD,
CMTD.PERCENT_ADD AS PERCENT_ADD,
CMTD.MULTIPLE_ADD AS MULTIPLE_ADD,
CMTD.ABSOLUTE_ADD AS ABSOLUTE_ADD
FROM C_MATERIAL CM,C_MATERIAL_TAB_DET CMTD,C_BUNKER CB
WHERE CM.ID=CMTD.C_MATERIAL_ID AND CM.ID=CB.C_MATERIAL_ID;
