--------------------------------------------------------
--  DDL for View V_LF_PRACTICE1
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_LF_PRACTICE1" ("C_PHASE_ID", "ID", "CMT_ID", "PHASE_SEQ_NO", "PRACTICE_ID", "DURATION", "PHASE_TYPE", "MATERIAL_TABLE", "MATERIAL_TABLE_ID", "END_TEMPERATURE", "GAS_FLOW", "GAS_FLOW_HIGH", "GAS_FLOW_LOW", "DISABLED", "DESCRIPTION") AS 
  SELECT
clpp.c_phase_id AS C_PHASE_ID,
clpp.ID as ID,
CMT.ID as CMT_ID,
CLPP.PHASE_SEQ_NO AS PHASE_SEQ_NO,
clpp.cl_practice_id AS PRACTICE_ID,
CLPP.DURATION AS DURATION,
CPH.PHASE_TYPE AS PHASE_TYPE,
CMT.MAT_TAB_NAME AS MATERIAL_TABLE,
CLPP.C_MATERIAL_TAB_ID AS MATERIAL_TABLE_ID,
CLPP.END_TEMPERATURE AS END_TEMPERATURE,
CLPP.GAS_FLOW AS GAS_FLOW,
CLPP.GAS_FLOW_HIGH AS GAS_FLOW_HIGH,
CLPP.GAS_FLOW_LOW AS GAS_FLOW_LOW,
CLPP.DISABLED AS DISABLED,
clpp.description
FROM CL_PRACTICE_PHASE CLPP, C_MATERIAL_TAB CMT,C_PHASE CPH
WHERE CPH.ID(+)=CLPP.C_PHASE_ID AND CMT.ID(+)=CLPP.C_MATERIAL_TAB_ID
ORDER BY PHASE_SEQ_NO;
