--------------------------------------------------------
--  DDL for View V_PLAN_OVERVIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PLAN_OVERVIEW" ("HEAT_NO", "STEEL_GRADE", "HEAT_STATUS", "STEEL_WEIGHT", "END_TIME", "S_HEAT_ID") AS 
  SELECT
SH.HEAT_NO AS HEAT_NO,
CSG.STEEL_GRADE AS STEEL_GRADE,
CHS.HEAT_STATUS_DESC_ENG AS HEAT_STATUS,
PH.STEEL_WEIGHT AS STEEL_WEIGHT,
PH.END_TIME AS END_TIME,
PH.S_HEAT_ID AS S_HEAT_ID
FROM P_HEAT PH, S_HEAT SH, C_STEEL_GRADE CSG,C_HEAT_STATUS CHS
WHERE SH.ID = PH.S_HEAT_ID AND CSG.ID = PH.C_STEEL_GRADE_ID AND CHS.ID = PH.C_HEAT_STATUS_ID;
