--------------------------------------------------------
--  DDL for View V_PLAN_OVERVIEW_OXYGEN
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PLAN_OVERVIEW_OXYGEN" ("STEP_SEQ_NO", "GAS_FLOW", "DUR", "GAS_AMOUNT", "START_ENERGY", "S_HEAT_ID") AS 
  SELECT
MPO.STEP_SEQ_NO AS STEP_SEQ_NO,
MPO.GAS_FLOW AS GAS_FLOW,
MPO.DURATION AS DUR,
MPO.GAS_AMOUNT AS GAS_AMOUNT,
MPO.START_ENERGY AS START_ENERGY,
MPP.S_HEAT_ID AS S_HEAT_ID
FROM ME_PRED_OXYGEN MPO, ME_PRED_PHASE MPP
WHERE MPP.ID = ME_PRED_PHASE_ID
ORDER BY STEP_SEQ_NO;
