--------------------------------------------------------
--  DDL for View V_PLAN_OVERVIEW_MATERIALS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PLAN_OVERVIEW_MATERIALS" ("S_HEAT_ID", "C_MATERIAL_ID", "MATERIAL_CODE") AS 
  SELECT
MPP.S_HEAT_ID AS S_HEAT_ID,
CM.ID AS C_MATERIAL_ID,
CM.MAT_CODE AS MATERIAL_CODE
FROM ME_PRED_PHASE MPP,C_MATERIAL CM, ME_PRED_CONTI_MAT MPCM
WHERE CM.ID = MPCM.C_MATERIAL_ID AND MPP.ID = MPCM.ME_PRED_PHASE_ID
ORDER BY STEP_SEQ_NO;
