--------------------------------------------------------
--  DDL for View V_PLAN_OVERVIEW_MATERIAL_ADD
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PLAN_OVERVIEW_MATERIAL_ADD" ("S_HEAT_ID", "BUNKER", "PHASE_TYPE", "MATERIAL", "WEIGHT") AS 
  SELECT
MPP.S_HEAT_ID AS S_HEAT_ID,
CB.BUNKER_NO AS BUNKER,
CP.PHASE_TYPE AS PHASE_TYPE,
CM.MAT_CODE AS MATERIAL,
MMR.MAT_WEIGHT AS WEIGHT
FROM ME_MATERIAL_RECIPE MMR, ME_PRED_PHASE MPP, C_MATERIAL CM, C_PHASE CP, C_BUNKER CB
WHERE CP.ID = MPP.C_PHASE_ID AND MPP.ID = MMR.ME_PRED_PHASE_ID AND CM.ID = MMR.C_MATERIAL_ID AND CB.ID = MMR.C_BUNKER_ID;
