--------------------------------------------------------
--  DDL for View V_PLAN_OVERVIEW_ELECTRIC
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PLAN_OVERVIEW_ELECTRIC" ("STEP_SEQ_NO", "DUR", "VOLTAGE_TAP", "TRANSFORMER_CURVE", "END_ENERGY", "S_HEAT_ID") AS 
  SELECT
MPE.STEP_SEQ_NO AS STEP_SEQ_NO,
MPE.DURATION AS DUR,
CE.VOLTAGE_TAP AS VOLTAGE_TAP,
CE.ELECTRODE_CONTROL AS TRANSFORMER_CURVE,
MPE.END_ENERGY AS END_ENERGY,
MPP.S_HEAT_ID AS S_HEAT_ID
FROM ME_PRED_PHASE MPP, ME_PRED_ELECTRIC MPE, CE_EL_POWER CE
WHERE MPP.ID = MPE.ME_PRED_PHASE_ID AND MPE.CE_EL_POWER_ID=CE.ID
ORDER BY STEP_SEQ_NO;
