--------------------------------------------------------
--  DDL for View VBH_PM_SETPOINT_DATA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VBH_PM_SETPOINT_DATA" ("SETPOINT_NAME", "STRAND1", "STRAND2", "STRAND3", "STRAND4") AS 
  SELECT
  'Cast Speed' as SETPOINT_NAME,
  (SELECT CAST_SPEED_SETP FROM PC_STRAND WHERE STRAND_NO=1) as STRAND1,
  (SELECT CAST_SPEED_SETP FROM PC_STRAND WHERE STRAND_NO=2) as STRAND2,
  (SELECT CAST_SPEED_SETP FROM PC_STRAND WHERE STRAND_NO=3) as STRAND3,
  (SELECT CAST_SPEED_SETP FROM PC_STRAND WHERE STRAND_NO=4) as STRAND4
from dual;
