--------------------------------------------------------
--  DDL for View VBH_PM_MAIN
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VBH_PM_MAIN" ("ID", "S_HEAT_ID", "HEAT_ID", "REMAINING_TIME", "C_STEEL_GRADE_ID", "STEEL_GRADE", "HEAT_SEQ_NO", "POS_IN_SEQ", "LADLE_NO", "ARM_NO", "STEEL_WEIGHT", "LIFTING_TEMP", "SUPERHEAT", "TUNDISH_WEIGHT", "LADLE_ARRIVAL_TIME", "CASTING_START_TIME", "LADLE_OPEN_WEIGHT", "LADLE_OPEN_TUNDISH_WEIGHT", "LADLE_CLOSE_TIME", "LADLE_CLOSE_WEIGHT", "LADLE_CLOSE_TUNDISH_WEIGHT", "LADLE_TARE_WEIGHT", "LADLE_SKULL_WEIGHT", "SHROUD_TYPE", "SHROUD_GAS", "SHROUD_AMOUNT", "LANCING", "LIQ_TEMP", "SHIFTID", "FLYING_TUNDISH", "CASTING_DURATION", "AVG_CAST_SPEED", "LADLE_COVER_USED", "LAST_IN_CAST", "LANCE_COUNT", "CASTING_FIN_TIME", "CREATED", "MODIFIED", "MOP") AS 
  SELECT "ID",
    "S_HEAT_ID" AS S_HEAT_ID,
    (SELECT HEAT_NO FROM S_HEAT WHERE ID="S_HEAT_ID"
    ) AS HEAT_ID,
    0 as "REMAINING_TIME",
    C_STEEL_GRADE_ID,
    (SELECT STEEL_GRADE FROM C_STEEL_GRADE CS WHERE CS.ID="C_STEEL_GRADE_ID"
    ) AS "STEEL_GRADE",
  "HEAT_SEQ_NO",
  "POS_IN_SEQ",
  (SELECT EQUIPMENT_NAME FROM C_EQUIPMENT CE WHERE CE.ID="C_EQUIPMENT_ID_LADLE" ) as "LADLE_NO",
  "ARM_NO",
  "STEEL_WEIGHT",
  0 as LIFTING_TEMP,
  0 as superheat,
  0 as tundish_weight,
  "LADLE_ARRIVAL_TIME",
  "LADLE_OPEN_TIME" as CASTING_START_TIME,
  "LADLE_OPEN_WEIGHT",
  "LADLE_OPEN_TUNDISH_WEIGHT",
  "LADLE_CLOSE_TIME",
  "LADLE_CLOSE_WEIGHT",
  "LADLE_CLOSE_TUNDISH_WEIGHT",
  "LADLE_TARE_WEIGHT",
  "LADLE_SKULL_WEIGHT",
  "SHROUD_TYPE",
  "SHROUD_GAS",
  "SHROUD_AMOUNT",
  "LANCING",
  "LIQ_TEMP",
  "SHIFTID",
  "FLYING_TUNDISH",
  "CASTING_DURATION",
  "AVG_CAST_SPEED",
  "LADLE_COVER_USED",
  "LAST_IN_CAST",
  "LANCE_COUNT",
  "CASTING_FIN_TIME",
  "CREATED",
  "MODIFIED",
  "MOP"
FROM PC_HEAT
WHERE C_HEAT_STATUS_ID=GET_HEAT_STATUS_ID(50);
