--------------------------------------------------------
--  DDL for View VEH_PM_DELAYS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VEH_PM_DELAYS" ("ID", "S_HEAT_ID", "PLANT_UNIT_ID", "UNIT_NO", "UNIT_CODE", "START_TIME", "END_TIME", "DELAY_CODE", "DELAY_CODE_ID", "COMMENT", "USER_NAME", "L3_SENT", "CREATED", "MODIFIED", "MOP") AS 
  SELECT "ID",
    "S_HEAT_ID",
    "PLANT_UNIT_ID",
    (SELECT PLANT_UNIT_NO FROM C_PLANT_UNIT cu WHERE cu.ID="PLANT_UNIT_ID") as UNIT_NO,
    (SELECT PLANT_UNIT_CODE FROM C_PLANT_UNIT cu WHERE cu.ID="PLANT_UNIT_ID") as UNIT_CODE,
    "START_TIME",
    "END_TIME",
    (SELECT "DELAY_CODE" FROM C_DELAY cd WHERE cd.ID = "DELAY_CODE_ID") as "DELAY_CODE",
    "DELAY_CODE_ID",
    "USER_DESCR" as "COMMENT",
    "USER_NAME",
    "L3_SENT",
    "CREATED",
    "MODIFIED",
    "MOP"
  FROM P_DELAY
  WHERE S_HEAT_ID in
    (SELECT S_HEAT_ID FROM VEH_PM_MAIN);
