--------------------------------------------------------
--  DDL for View VEH_BASKET_STATUS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VEH_BASKET_STATUS" ("ID", "BASKET_NO", "BASKET_DESC_ENG", "STATUS", "TOTAL_WEIGHT") AS 
  SELECT ID,
  BASKET_NO,
  BASKET_DESC_ENG,
  DECODE(TOTAL_WEIGHT,NULL, 'Empty', 'Loaded') as STATUS,
  TOTAL_WEIGHT FROM
(SELECT ID,
  EQUIPMENT_NAME as BASKET_NO,
  DESCRIPTION as BASKET_DESC_ENG,
  (SELECT SUM (MAT_WEIGHT)
    FROM PE_BASKET_DET
    WHERE PE_BASKET_ID IN
      (SELECT ID FROM PE_BASKET WHERE C_EQUIPMENT_ID_BASKET=cb.ID AND S_HEAT_ID IS NULL
      )
  ) AS TOTAL_WEIGHT
FROM C_EQUIPMENT cb WHERE C_EQUIPMENT_TYPE_ID=(SELECT ID FROM C_EQUIPMENT_TYPE WHERE TYPE_NAME='Basket'));
