--------------------------------------------------------
--  DDL for View VEH_PM_BASKET_ADD
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VEH_PM_BASKET_ADD" ("S_HEAT_ID", "C_EQUIPMENT_ID_BASKET", "BASKET_NO", "LAYER_SEQ_NO", "C_MATERIAL_ID", "MAT_CODE", "MAT_WEIGHT", "MAT_TEMPERATURE") AS 
  SELECT
  pm_main.S_HEAT_ID,
  pb.C_EQUIPMENT_ID_BASKET,
  (SELECT EQUIPMENT_NAME FROM C_EQUIPMENT c WHERE c.ID=pb.C_EQUIPMENT_ID_BASKET) BASKET_NO,
  "LAYER_SEQ_NO" ,
	"C_MATERIAL_ID" ,
	(SELECT MAT_CODE FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_CODE,
  "MAT_WEIGHT" ,
	"MAT_TEMPERATURE"
FROM (SELECT * FROM PE_BASKET pe,PE_BASKET_DET ped WHERE pe.ID=ped.PE_BASKET_ID) pb,
      VEH_PM_MAIN pm_main
WHERE pb.S_HEAT_ID=pm_main.S_HEAT_ID;
