--------------------------------------------------------
--  DDL for View VEH_PM_BLOW_REPORT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VEH_PM_BLOW_REPORT" ("ID", "C_PLANT_UNIT_ID", "UNIT_CODE", "UNIT_NO", "C_EQUIP_ID", "C_EQUIP_NAME", "BLOWN_MATERIAL", "MAT_FLOW", "MAT_AMOUNT", "S_HEAT_ID", "CREATED", "MODIFIED", "MOP") AS 
  SELECT ID,
  C_PLANT_UNIT_ID,
  (SELECT PLANT_UNIT_CODE FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_CODE,
  (SELECT PLANT_UNIT_NO FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_NO,
  "C_EQUIP_ID",
  (SELECT EQUIPMENT_NAME FROM C_EQUIPMENT e WHERE e.ID="C_EQUIP_ID") "C_EQUIP_NAME",
  BLOWN_MATERIAL,
  MAT_FLOW,
  MAT_AMOUNT,
  S_HEAT_ID,
  CREATED,
  MODIFIED,
  MOP
FROM PE_BLOW_REPORT;
