--------------------------------------------------------
--  DDL for View VEH_CASTER_INFO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VEH_CASTER_INFO" ("BC_REM_LADLE_WEIGHT", "BC_REM_LADLE_TIME", "BC_CASTING_SPEED_STR1", "BC_CASTING_SPEED_STR2", "BC_CASTING_SPEED_STR3", "BC_CASTING_SPEED_STR4", "BC_TUNDISH_TEMP", "SC1_REM_LADLE_WEIGHT", "SC1_REM_LADLE_TIME", "SC1_CASTING_SPEED_STR1", "SC1_CASTING_SPEED_STR2", "SC1_TUNDISH_TEMP", "SC2_REM_LADLE_WEIGHT", "SC2_REM_LADLE_TIME", "SC2_CASTING_SPEED_STR1", "SC2_CASTING_SPEED_STR2", "SC2_TUNDISH_TEMP") AS 
  SELECT
(SELECT REMAINING_LADLE_WEIGHT FROM P_CASTER_STATUS WHERE PLANT_UNIT='BC' and HEAT_STATUS_ID=50) AS BC_REM_LADLE_WEIGHT,
(SELECT REMAINING_LADLE_TIME FROM P_CASTER_STATUS WHERE PLANT_UNIT='BC' and HEAT_STATUS_ID=50) AS BC_REM_LADLE_TIME,
(SELECT CASTING_SPEED_STR1 FROM P_CASTER_STATUS WHERE PLANT_UNIT='BC' and HEAT_STATUS_ID=50) AS BC_CASTING_SPEED_STR1,
(SELECT CASTING_SPEED_STR2 FROM P_CASTER_STATUS WHERE PLANT_UNIT='BC' and HEAT_STATUS_ID=50) AS BC_CASTING_SPEED_STR2,
(SELECT CASTING_SPEED_STR3 FROM P_CASTER_STATUS WHERE PLANT_UNIT='BC' and HEAT_STATUS_ID=50) AS BC_CASTING_SPEED_STR3,
(SELECT CASTING_SPEED_STR4 FROM P_CASTER_STATUS WHERE PLANT_UNIT='BC' and HEAT_STATUS_ID=50) AS BC_CASTING_SPEED_STR4,
(SELECT TUNDISH_TEMPERATURE FROM P_CASTER_STATUS WHERE PLANT_UNIT='BC' and HEAT_STATUS_ID=50) AS BC_TUNDISH_TEMP,
(SELECT REMAINING_LADLE_WEIGHT FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=1 and HEAT_STATUS_ID=50) AS SC1_REM_LADLE_WEIGHT,
(SELECT REMAINING_LADLE_TIME FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=1 and HEAT_STATUS_ID=50) AS SC1_REM_LADLE_TIME,
(SELECT CASTING_SPEED_STR1 FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=1 and HEAT_STATUS_ID=50) AS SC1_CASTING_SPEED_STR1,
(SELECT CASTING_SPEED_STR2 FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=1 and HEAT_STATUS_ID=50) AS SC1_CASTING_SPEED_STR2,
(SELECT TUNDISH_TEMPERATURE FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=1 and HEAT_STATUS_ID=50) AS SC1_TUNDISH_TEMP,
(SELECT REMAINING_LADLE_WEIGHT FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=2 and HEAT_STATUS_ID=50) AS SC2_REM_LADLE_WEIGHT,
(SELECT REMAINING_LADLE_TIME FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=2 and HEAT_STATUS_ID=50) AS SC2_REM_LADLE_TIME,
(SELECT CASTING_SPEED_STR1 FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=2 and HEAT_STATUS_ID=50) AS SC2_CASTING_SPEED_STR1,
(SELECT CASTING_SPEED_STR2 FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=2 and HEAT_STATUS_ID=50) AS SC2_CASTING_SPEED_STR2,
(SELECT TUNDISH_TEMPERATURE FROM P_CASTER_STATUS WHERE PLANT_UNIT='SC' and PLANT_UNIT_NO=2 and HEAT_STATUS_ID=50) AS SC2_TUNDISH_TEMP
FROM DUAL;
