--------------------------------------------------------
--  DDL for View VEH_HM_STATUS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VEH_HM_STATUS" ("ID", "LADLE_NO", "LADLE_DESC_ENG", "STATUS", "TOTAL_WEIGHT") AS 
  SELECT ID,
  LADLE_NO,
  LADLE_DESC_ENG,
  DECODE(TOTAL_WEIGHT,NULL, 'Empty', 'Loaded') as STATUS,
  TOTAL_WEIGHT FROM
  (
    SELECT ID,
    EQUIPMENT_NAME LADLE_NO,
    DESCRIPTION LADLE_DESC_ENG,
    (SELECT SUM (INIT_WEIGHT) as TOTAL_WEIGHT FROM PE_HOT_METAL pe WHERE pe.ID IN (SELECT ID FROM PE_HOT_METAL WHERE C_EQUIPMENT_ID_LADLE=cl.ID AND S_HEAT_ID IS NULL )) AS TOTAL_WEIGHT
FROM C_EQUIPMENT cl WHERE C_EQUIPMENT_TYPE_ID=(SELECT ID FROM C_EQUIPMENT_TYPE WHERE TYPE_NAME='HotMetalLadle'));
