--------------------------------------------------------
--  DDL for View VEH_PM_TAPPING_ADD
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VEH_PM_TAPPING_ADD" ("S_HEAT_ID", "C_MATERIAL_TAB_ID", "ADD_SEQUENCE_NO", "C_MATERIAL_ID", "MAT_CODE", "RELATIVE_ADD", "PERCENT_ADD", "MULTIPLE_ADD", "ABSOLUTE_ADD") AS 
  SELECT
  pm_main.S_HEAT_ID,
  C_MATERIAL_TAB_ID,
  ADD_SEQUENCE_NO,
  C_MATERIAL_ID,
  (SELECT MAT_CODE FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_CODE,
  RELATIVE_ADD,
  PERCENT_ADD,
  MULTIPLE_ADD,
  ABSOLUTE_ADD
FROM C_MATERIAL_TAB_DET cd, VEH_PM_MAIN pm_main
WHERE cd.C_MATERIAL_TAB_ID=pm_main.C_MATERIAL_TAB_ID_TAP;
