--------------------------------------------------------
--  DDL for View VEM_PRED_PHASES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VEM_PRED_PHASES" ("ID", "S_HEAT_ID", "PHASE_SEQ_NO", "PHASE_TYPE", "PRED_DURATION", "CURR_DURATION", "END_PHASE_ENERGY", "C_MATERIAL_TAB_ID", "PRED_STEEL_WEIGHT", "PRED_SLAG_WEIGHT", "CURR_STEEL_WEIGHT", "CURR_SLAG_WEIGHT", "CURR_CONTI_DRI", "FEED_SPEED_DRI", "PRED_CONTI_DRI", "CURR_CONTI_LIME", "FEED_SPEED_LIME", "PRED_CONTI_LIME", "CURR_CONTI_DOLOMITE", "FEED_SPEED_DOLOMITE", "PRED_CONTI_DOLOMITE", "CURR_CONTI_SPEC", "FEED_SPEED_SPEC", "PRED_CONTI_SPEC", "CURR_CARBON_BLOWN", "PRED_CARBON_BLOWN", "CURR_O2_BLOWN", "PRED_O2_BLOWN", "CURR_EL_ENERGY", "PRED_EL_ENERGY", "CURR_FUEL", "PRED_FUEL") AS 
  SELECT mp.ID,
  mp.S_HEAT_ID,
  PHASE_SEQ_NO,
  (select phase_type from c_phase where mp.C_PHASE_ID = id) as phase_type,
  PRED_DURATION,
  CURR_DURATION,
  END_PHASE_ENERGY,
  C_MATERIAL_TAB_ID,
  PRED_STEEL_WEIGHT,
  PRED_SLAG_WEIGHT,
  CURR_STEEL_WEIGHT,
  CURR_SLAG_WEIGHT,
  CURR_CONTI_DRI,
  FEED_SPEED_DRI,
  PRED_CONTI_DRI,
  CURR_CONTI_LIME,
  FEED_SPEED_LIME,
  PRED_CONTI_LIME,
  CURR_CONTI_DOLOMITE,
  FEED_SPEED_DOLOMITE,
  PRED_CONTI_DOLOMITE,
  CURR_CONTI_SPEC,
  FEED_SPEED_SPEC,
  PRED_CONTI_SPEC,
  CURR_CARBON_BLOWN,
  PRED_CARBON_BLOWN,
  CURR_O2_BLOWN,
  PRED_O2_BLOWN,
  CURR_EL_ENERGY,
  PRED_EL_ENERGY,
  CURR_FUEL,
  PRED_FUEL
FROM ME_PRED_PHASE mp, PE_HEAT pe, S_HEAT s
where
  mp.s_heat_id=pe.s_heat_id
  and mp.s_heat_id=s.id
  and pe.c_heat_status_id = get_heat_status_id(20);
