--------------------------------------------------------
--  DDL for View VGH_LAB_MAT_ANA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_LAB_MAT_ANA" ("SAMPLE_TIME", "SUPPLIER_NAME", "DESCRIPTION", "REMARK", "SIZE_GM_MT", "TRUCK_NO", "C_MATERIAL_ID", "MAT_CODE", "LOI", "CAO", "MGO", "SIO", "ZRO", "CAF", "FEO", "TIO", "MNO", "CRO", "AL2O3", "MOISTURE", "F_C", "C_", "VM", "MN", "SI", "CA", "FE", "AL", "P", "S", "CR", "MO", "NI", "TI", "PB", "B", "NB") AS 
  SELECT SAMPLE_TIME AS SAMPLE_TIME,
    SUPPLIER_NAME    AS SUPPLIER_NAME,
    DESCRIPTION      AS DESCRIPTION,
    REMARK AS REMARK,
    SIZE_GM_MT AS SIZE_GM_MT,
    TRUCK_NO   AS TRUCK_NO,
    C_MATERIAL_ID,
    (SELECT MAT_CODE FROM C_MATERIAL cm WHERE cm.ID=C_MATERIAL_ID) MAT_CODE,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='LOI'
      )
    ) AS "LOI" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='CaO'
      )
    ) AS "CAO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='MgO'
      )
    ) AS "MGO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='SiO2'
      )
    ) AS "SIO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='ZrO2'
      )
    ) AS "ZRO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='CaF2'
      )
    ) AS "CAF" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Fe2O3'
      )
    ) AS "FEO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='TiO2'
      )
    ) AS "TIO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='MnO'
      )
    ) AS "MNO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Cr2O3'
      )
    ) AS "CRO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Al2O3'
      )
    ) AS "AL2O3" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='MOISTURE'
      )
    ) AS "MOISTURE" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='FC'
      )
    ) AS "F_C" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C'
      )
    ) AS "C_" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='VM'
      )
    ) AS "VM" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Mn'
      )
    ) AS "MN" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Si'
      )
    ) AS "SI" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Ca'
      )
    ) AS "CA" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Fe'
      )
    ) AS "FE" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Al'
      )
    ) AS "AL" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='P'
      )
    ) AS "P" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='S'
      )
    ) AS "S" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Cr'
      )
    ) AS "CR" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Mo'
      )
    ) AS "MO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Ni'
      )
    ) AS "NI" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Ti'
      )
    ) AS "TI" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Pb'
      )
    ) AS "PB" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='B'
      )
    ) AS "B" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT
    WHERE P_LAB_MAT.ID =P_LAB_MAT_ID
    AND C_ELEMENT_ID   =
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Nb'
      )
    ) AS "NB"
  FROM P_LAB_MAT;
