--------------------------------------------------------
--  DDL for View VGH_WIRE_STRANDS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_WIRE_STRANDS" ("ID", "C_PLANT_UNIT_ID", "UNIT_CODE", "UNIT_NO", "MAT_CODE", "WIRE_FEEDER_NO", "C_MATERIAL_ID", "MAT_AVAILABLE_L1", "MAT_AVAILABLE_L2", "MAT_AMOUNT", "MAX_FEED_RATE", "MIN_FEED_RATE", "CREATED", "MODIFIED", "MOP", "STRAND_NO") AS 
  SELECT ID,
  C_PLANT_UNIT_ID,
  (SELECT PLANT_UNIT_CODE FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_CODE,
  (SELECT PLANT_UNIT_NO FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_NO,
  (SELECT MAT_CODE FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_CODE,
  WIRE_FEEDER_NO,
  C_MATERIAL_ID,
  MAT_AVAILABLE_L1,
  MAT_AVAILABLE_L2,
  MAT_AMOUNT,
  MAX_FEED_RATE,
  MIN_FEED_RATE,
  CREATED,
  MODIFIED,
  MOP,
  STRAND_NO
FROM C_WIRE_STRAND;
