--------------------------------------------------------
--  DDL for View VGH_CHARGED_BUNKER_MAT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_CHARGED_BUNKER_MAT" ("ID", "C_PLANT_UNIT_ID", "UNIT_CODE", "UNIT_NO", "BUNKER_NO", "C_MATERIAL_ID", "MAT_CODE", "MAT_REPORT_GROUP", "MAT_WEIGHT", "DISCHARGE_TIME", "S_HEAT_ID") AS 
  SELECT ID,
  C_PLANT_UNIT_ID,
  (SELECT PLANT_UNIT_CODE FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_CODE,
  (SELECT PLANT_UNIT_NO FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_NO,
  (SELECT BUNKER_NO FROM C_BUNKER CB WHERE CB.ID=C_BUNKER_ID) BUNKER_NO,
  C_MATERIAL_ID,
  (SELECT MAT_CODE FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_CODE,
  (SELECT REPORT_GROUP FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_REPORT_GROUP,
 MAT_WEIGHT,
  DISCHARGE_TIME, S_HEAT_ID
FROM P_MAT_REPORT;
