--------------------------------------------------------
--  DDL for View VGH_EQUIPMENT_LIFE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_EQUIPMENT_LIFE" ("P_EQUIPMENT_LIFE_ID", "EQUIPMENT_LIFE_VALUE", "C_EQUIPMENT_TYPE_ID", "EQUIPMENT_NAME", "IN_USE", "SERIAL_NUMBER", "DESCRIPTION", "PRODUCER", "EQUIPMENT_NO", "COUNTER_NAME", "EQ_COUNTER_DESCRIPTION", "TYPE_NAME", "C_EQUIPMENT_ID", "C_EQUIPMENT_COUNTER_ID") AS 
  SELECT
 (SELECT ID FROM p_equipment_life p WHERE p.c_equipment_id=ct.id AND p.C_EQUIPMENT_COUNTER_ID=cc.ID)  P_EQUIPMENT_LIFE_ID,
 (SELECT p.EQUIPMENT_LIFE_VALUE FROM p_equipment_life p WHERE p.c_equipment_id=ct.id AND p.C_EQUIPMENT_COUNTER_ID=cc.ID)  EQUIPMENT_LIFE_VALUE,
  ct.C_EQUIPMENT_TYPE_ID C_EQUIPMENT_TYPE_ID,
  ct.EQUIPMENT_NAME EQUIPMENT_NAME,
  ct.IN_USE IN_USE,
  ct.SERIAL_NUMBER SERIAL_NUMBER,
  ct.DESCRIPTION DESCRIPTION,
  ct.PRODUCER PRODUCER,
  ct.EQUIPMENT_NO EQUIPMENT_NO,
  cc.COUNTER_NAME COUNTER_NAME,
  cc.DESCRIPTION EQ_COUNTER_DESCRIPTION,
  ctype.TYPE_NAME TYPE_NAME,
  ct.ID as C_EQUIPMENT_ID,
  cc.ID  as C_EQUIPMENT_COUNTER_ID
FROM C_EQUIPMENT ct,C_EQUIPMENT_X_C_T x, C_EQUIPMENT_COUNTER cc, c_equipment_type ctype
WHERE
ct.c_equipment_type_id=x.c_equipment_type_id AND
cc.ID=x.c_equipment_counter_id AND
ct.c_equipment_type_id=ctype.ID;
