--------------------------------------------------------
--  DDL for View VGH_EQ_TREE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_EQ_TREE" ("ID", "C_EQUIPMENT_ID", "C_EQUIPMENT_ID_PARENT", "ORDER_IN_LEVEL", "C_EQUIPMENT_TYPE_ID", "EQUIPMENT_NAME", "IN_USE", "SERIAL_NUMBER", "DESCRIPTION", "PRODUCER", "EQUIPMENT_NO", "EQUIPMENT_NAME_PARENT") AS 
  SELECT P_EQUIPMENT_TREE.ID ID,
P_EQUIPMENT_TREE.C_EQUIPMENT_ID C_EQUIPMENT_ID,
P_EQUIPMENT_TREE.C_EQUIPMENT_ID_PARENT C_EQUIPMENT_ID_PARENT,
P_EQUIPMENT_TREE.ORDER_IN_LEVEL ORDER_IN_LEVEL,
C_EQUIPMENT.C_EQUIPMENT_TYPE_ID C_EQUIPMENT_TYPE_ID,
C_EQUIPMENT.EQUIPMENT_NAME EQUIPMENT_NAME,
C_EQUIPMENT.IN_USE IN_USE,
C_EQUIPMENT.SERIAL_NUMBER SERIAL_NUMBER,
C_EQUIPMENT.DESCRIPTION DESCRIPTION,
C_EQUIPMENT.PRODUCER PRODUCER,
C_EQUIPMENT.EQUIPMENT_NO EQUIPMENT_NO,
(SELECT EQUIPMENT_NAME FROM C_EQUIPMENT WHERE ID=C_EQUIPMENT_ID_PARENT) EQUIPMENT_NAME_PARENT
FROM
P_EQUIPMENT_TREE, C_EQUIPMENT
WHERE P_EQUIPMENT_TREE.C_EQUIPMENT_ID=C_EQUIPMENT.ID;
