--------------------------------------------------------
--  DDL for View VGH_ME_ANA_HIST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_ME_ANA_HIST" ("ID", "CREATED", "C_PLANT_UNIT_ID", "C", "Mn", "Si", "P", "S", "Al", "Cu", "Cr", "Mo", "Ni", "V", "Ti", "Nb", "Ca", "Co", "Pb", "W", "Mg", "Ce", "B", "As", "Sn", "Bi", "Sb", "Zn", "Ta", "Zr", "Se", "O", "N", "H", "La", "Fe", "CaO", "SiO2", "Al2O3", "FeO", "MgO", "Cr2O3", "P2O5", "MnO", "NiO", "TiO2", "TiFeO", "CaF2", "CaC2", "Fe2O3") AS 
  SELECT   ROWNUM AS ID, "CREATED",C_PLANT_UNIT_ID, "C","Mn","Si","P","S","Al","Cu","Cr","Mo","Ni","V","Ti","Nb","Ca","Co","Pb","W","Mg","Ce","B","As","Sn","Bi","Sb","Zn","Ta","Zr","Se","O","N","H","La","Fe","CaO","SiO2","Al2O3","FeO","MgO","Cr2O3","P2O5","MnO","NiO","TiO2","TiFeO","CaF2","CaC2","Fe2O3" FROM
(SELECT
  ME.CREATED,
  1 AS C_PLANT_UNIT_ID,
   MAX(DECODE(ELE_SYMBOL,'C',ELE_AMOUNT * 100, null)) "C",
  MAX(DECODE(ELE_SYMBOL,'Mn',ELE_AMOUNT * 100, null)) "Mn",
  MAX(DECODE(ELE_SYMBOL,'Si',ELE_AMOUNT * 100, null)) "Si",
  MAX(DECODE(ELE_SYMBOL,'P',ELE_AMOUNT * 100, null)) "P",
  MAX(DECODE(ELE_SYMBOL,'S',ELE_AMOUNT * 100, null)) "S",
  MAX(DECODE(ELE_SYMBOL,'Al',ELE_AMOUNT * 100, null)) "Al",
  MAX(DECODE(ELE_SYMBOL,'Cu',ELE_AMOUNT * 100, null)) "Cu",
  MAX(DECODE(ELE_SYMBOL,'Cr',ELE_AMOUNT * 100, null)) "Cr",
  MAX(DECODE(ELE_SYMBOL,'Mo',ELE_AMOUNT * 100, null)) "Mo",
  MAX(DECODE(ELE_SYMBOL,'Ni',ELE_AMOUNT * 100, null)) "Ni",
  MAX(DECODE(ELE_SYMBOL,'V',ELE_AMOUNT * 100, null)) "V",
  MAX(DECODE(ELE_SYMBOL,'Ti',ELE_AMOUNT * 100, null)) "Ti",
  MAX(DECODE(ELE_SYMBOL,'Nb',ELE_AMOUNT * 100, null)) "Nb",
  MAX(DECODE(ELE_SYMBOL,'Ca',ELE_AMOUNT * 100, null)) "Ca",
  MAX(DECODE(ELE_SYMBOL,'Co',ELE_AMOUNT * 100, null)) "Co",
  MAX(DECODE(ELE_SYMBOL,'Pb',ELE_AMOUNT * 100, null)) "Pb",
  MAX(DECODE(ELE_SYMBOL,'W',ELE_AMOUNT * 100, null)) "W",
  MAX(DECODE(ELE_SYMBOL,'Mg',ELE_AMOUNT * 100, null)) "Mg",
  MAX(DECODE(ELE_SYMBOL,'Ce',ELE_AMOUNT * 100, null)) "Ce",
  MAX(DECODE(ELE_SYMBOL,'B',ELE_AMOUNT * 100, null)) "B",
  MAX(DECODE(ELE_SYMBOL,'As',ELE_AMOUNT * 100, null)) "As",
  MAX(DECODE(ELE_SYMBOL,'Sn',ELE_AMOUNT * 100, null)) "Sn",
  MAX(DECODE(ELE_SYMBOL,'Bi',ELE_AMOUNT * 100, null)) "Bi",
  MAX(DECODE(ELE_SYMBOL,'Sb',ELE_AMOUNT * 100, null)) "Sb",
  MAX(DECODE(ELE_SYMBOL,'Zn',ELE_AMOUNT * 100, null)) "Zn",
  MAX(DECODE(ELE_SYMBOL,'Ta',ELE_AMOUNT * 100, null)) "Ta",
  MAX(DECODE(ELE_SYMBOL,'Zr',ELE_AMOUNT * 100, null)) "Zr",
  MAX(DECODE(ELE_SYMBOL,'Se',ELE_AMOUNT * 100, null)) "Se",
  MAX(DECODE(ELE_SYMBOL,'O',ELE_AMOUNT * 100, null)) "O",
  MAX(DECODE(ELE_SYMBOL,'N',ELE_AMOUNT * 100, null)) "N",
  MAX(DECODE(ELE_SYMBOL,'H',ELE_AMOUNT * 100, null)) "H",
  MAX(DECODE(ELE_SYMBOL,'La',ELE_AMOUNT * 100, null)) "La",
  MAX(DECODE(ELE_SYMBOL,'Fe',ELE_AMOUNT * 100, null)) "Fe",
  MAX(DECODE(ELE_SYMBOL,'CaO',ELE_AMOUNT * 100, null)) "CaO",
  MAX(DECODE(ELE_SYMBOL,'SiO2',ELE_AMOUNT * 100, null)) "SiO2",
  MAX(DECODE(ELE_SYMBOL,'Al2O3',ELE_AMOUNT * 100, null)) "Al2O3",
  MAX(DECODE(ELE_SYMBOL,'FeO',ELE_AMOUNT * 100, null)) "FeO",
  MAX(DECODE(ELE_SYMBOL,'MgO',ELE_AMOUNT * 100, null)) "MgO",
  MAX(DECODE(ELE_SYMBOL,'Cr2O3',ELE_AMOUNT * 100, null)) "Cr2O3",
  MAX(DECODE(ELE_SYMBOL,'P2O5',ELE_AMOUNT * 100, null)) "P2O5",
  MAX(DECODE(ELE_SYMBOL,'MnO',ELE_AMOUNT * 100, null)) "MnO",
  MAX(DECODE(ELE_SYMBOL,'NiO',ELE_AMOUNT * 100, null)) "NiO",
  MAX(DECODE(ELE_SYMBOL,'TiO2',ELE_AMOUNT * 100, null)) "TiO2",
  MAX(DECODE(ELE_SYMBOL,'TiFeO',ELE_AMOUNT * 100, null)) "TiFeO",
  MAX(DECODE(ELE_SYMBOL,'CaF2',ELE_AMOUNT * 100, null)) "CaF2",
  MAX(DECODE(ELE_SYMBOL,'CaC2',ELE_AMOUNT * 100, null)) "CaC2",
  MAX(DECODE(ELE_SYMBOL,'Fe2O3',ELE_AMOUNT * 100, null)) "Fe2O3"
  FROM ME_HEAT_HIST_ANA ME, C_ELEMENT
  WHERE C_ELEMENT.ID=ME.C_ELEMENT_ID
  AND ME.ME_HEAT_ID in (SELECT ID FROM ME_HEAT WHERE S_HEAT_ID IN (SELECT S_HEAT_ID FROM PE_HEAT WHERE C_PLANT_UNIT_ID=1))
  GROUP BY ME.CREATED) ;
