--------------------------------------------------------
--  DDL for View VGH_CHARGED_WIRES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_CHARGED_WIRES" ("ID", "S_HEAT_ID", "C_PLANT_UNIT_ID", "UNIT_CODE", "UNIT_NO", "STRAND_NO", "WIRE_FEEDER_NO", "C_MATERIAL_ID", "MAT_CODE", "LEGTH_CONSUMED", "WEIGHT_CONSUMED", "FILL_RATIO", "START_TIME", "STOP_TIME") AS 
  SELECT ID,
  S_HEAT_ID,
  C_PLANT_UNIT_ID,
  (SELECT PLANT_UNIT_CODE FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_CODE,
  (SELECT PLANT_UNIT_NO FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_NO,
  (SELECT STRAND_NO FROM C_WIRE_STRAND CB WHERE CB.ID=C_WIRE_STRAND_ID) STRAND_NO,
  (SELECT WIRE_FEEDER_NO FROM C_WIRE_STRAND CB WHERE CB.ID=C_WIRE_STRAND_ID) WIRE_FEEDER_NO,
  C_MATERIAL_ID,
  (SELECT MAT_CODE FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_CODE,
  LEGTH_CONSUMED,
  WEIGHT_CONSUMED,
  FILL_RATIO,
  START_TIME,
  STOP_TIME
FROM P_WIRE_REPORT;
