--------------------------------------------------------
--  DDL for View VGH_EQUIPMENT_TYPE_X_COUNTER
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_EQUIPMENT_TYPE_X_COUNTER" ("C_EQUIPMENT_TYPE_ID", "TYPE_NAME", "C_EQUIPMENT_COUNTER_ID", "COUNTER_NAME", "USED") AS 
  SELECT
ct.ID as C_EQUIPMENT_TYPE_ID,
ct.TYPE_NAME,
cc.ID as C_EQUIPMENT_COUNTER_ID,
cc.COUNTER_NAME,
(SELECT count(1) FROM C_EQUIPMENT_X_C_T x WHERE x.C_EQUIPMENT_TYPE_ID=ct.ID and x.C_EQUIPMENT_COUNTER_ID=cc.ID) AS USED
FROM C_EQUIPMENT_TYPE ct,C_EQUIPMENT_COUNTER cc;
