--------------------------------------------------------
--  DDL for View VGH_LAB_ANA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VGH_LAB_ANA" ("ID", "S_HEAT_ID", "HEAT_ID", "SAMPLE_ID", "C_SAMPLE_TYPE_ID", "SAMPLE_PLACE", "SAMPLE_PHASE_ID", "SAMPLE_PHASE", "TIME_ANNOUNCE", "TIME_ANALYSE", "Cu", "V", "Ti", "Co", "W", "Se", "Ca", "As", "Sn", "H", "MgO", "P", "Sb", "Zr", "SiO2", "P2O5", "CaC2", "Mo", "Bi", "Cr2O3", "Ta", "CaO", "CaF2", "C", "Si", "Nb", "B", "MnO", "Ni", "Pb", "Mg", "Ce", "Zn", "O", "N", "Fe", "NiO", "TiO2", "Mn", "S", "Al", "Cr", "La", "Al2O3", "FeO", "TiFeO", "Fe2O3", "V2O5", "SO3") AS 
  SELECT "ID",
    "S_HEAT_ID" AS S_HEAT_ID,
    (SELECT HEAT_NO FROM S_HEAT WHERE ID="S_HEAT_ID"
    ) AS HEAT_ID,
    SAMPLE_ID,
    C_SAMPLE_TYPE_ID,
    C_PLANT_UNIT_ID AS SAMPLE_PLACE,
    C_PHASE_ID as SAMPLE_PHASE_ID,
    (SELECT PHASE_TYPE FROM C_PHASE CP WHERE CP.ID=C_PHASE_ID) as SAMPLE_PHASE,
    TIME_ANNOUNCE,
    TIME_ANALYSE ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Cu'
      )
    ) AS "Cu" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='V'
      )
    ) AS "V" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Ti'
      )
    ) AS "Ti" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Co'
      )
    ) AS "Co" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='W'
      )
    ) AS "W" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Se'
      )
    ) AS "Se" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Ca'
      )
    ) AS "Ca" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='As'
      )
    ) AS "As" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Sn'
      )
    ) AS "Sn" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='H'
      )
    ) AS "H" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='MgO'
      )
    ) AS "MgO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='P'
      )
    ) AS "P" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Sb'
      )
    ) AS "Sb" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Zr'
      )
    ) AS "Zr" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='SiO2'
      )
    ) AS "SiO2" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='P2O5'
      )
    ) AS "P2O5" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='CaC2'
      )
    ) AS "CaC2" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Mo'
      )
    ) AS "Mo" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Bi'
      )
    ) AS "Bi" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Cr2O3'
      )
    ) AS "Cr2O3" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Ta'
      )
    ) AS "Ta" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='CaO'
      )
    ) AS "CaO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='CaF2'
      )
    ) AS "CaF2" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C'
      )
    ) AS "C" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Si'
      )
    ) AS "Si" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Nb'
      )
    ) AS "Nb" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='B'
      )
    ) AS "B" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='MnO'
      )
    ) AS "MnO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Ni'
      )
    ) AS "Ni" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Pb'
      )
    ) AS "Pb" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Mg'
      )
    ) AS "Mg" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Ce'
      )
    ) AS "Ce" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Zn'
      )
    ) AS "Zn" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='O'
      )
    ) AS "O" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='N'
      )
    ) AS "N" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Fe'
      )
    ) AS "Fe" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='NiO'
      )
    ) AS "NiO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='TiO2'
      )
    ) AS "TiO2" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Mn'
      )
    ) AS "Mn" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='S'
      )
    ) AS "S" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Al'
      )
    ) AS "Al" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Cr'
      )
    ) AS "Cr" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='La'
      )
    ) AS "La" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Al2O3'
      )
    ) AS "Al2O3" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='FeO'
      )
    ) AS "FeO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='TiFeO'
      )
    ) AS "TiFeO" ,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='Fe2O3'
      )
    ) AS "Fe2O3",
     (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='V2O5'
      )
    ) AS "V2O5",
     (SELECT ELE_AMOUNT
    FROM P_LAB_ANA
    WHERE P_LAB_ID  =pl.ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='SO3'
      )
    ) AS "SO3"
  FROM P_LAB pl;
