--------------------------------------------------------
--  DDL for View VLH_PM_BUNKER_MAT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VLH_PM_BUNKER_MAT" ("ID", "C_PLANT_UNIT_ID", "UNIT_CODE", "UNIT_NO", "BUNKER_NO", "C_MATERIAL_ID", "MAT_CODE", "MAT_DESC", "MAT_AVAILABLE_L1", "MAT_AVAILABLE_L2", "MAT_AMOUNT", "CURR_TEMPERATURE", "CONTI_FEED_USAGE", "MAX_FEED_RATE", "MIN_FEED_RATE") AS 
  SELECT ID,
  C_PLANT_UNIT_ID,
  (SELECT PLANT_UNIT_CODE FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_CODE,
  (SELECT PLANT_UNIT_NO FROM C_PLANT_UNIT pu where C_PLANT_UNIT_ID=pu.ID) UNIT_NO,
  BUNKER_NO,
  C_MATERIAL_ID,
  (SELECT MAT_CODE FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_CODE,
  (SELECT DESCRIPTION_ENG FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_DESC,
  MAT_AVAILABLE_L1,
  MAT_AVAILABLE_L2,
  MAT_AMOUNT,
  CURR_TEMPERATURE,
  CONTI_FEED_USAGE,
  MAX_FEED_RATE,
  MIN_FEED_RATE
FROM C_BUNKER;
