--------------------------------------------------------
--  DDL for View VLH_FIN_HEATS_CONFIRM
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VLH_FIN_HEATS_CONFIRM" ("ID", "S_HEAT_ID", "HEAT_ID", "C_HEAT_STATUS_ID", "STATUS", "C_PLANT_UNIT_ID", "LAST_PLANT_UNIT", "LAST_PLANT_UNIT_NO", "STEEL_GRADE", "C_STEEL_GRADE_ID", "STEEL_WEIGHT", "SLAG_WEIGHT", "STEEL_TEMPERATURE") AS 
  SELECT "ID",
    "S_HEAT_ID",
    (SELECT HEAT_NO FROM S_HEAT WHERE ID="S_HEAT_ID"
    ) AS HEAT_ID,
    "C_HEAT_STATUS_ID",
    (SELECT HEAT_STATUS_DESC_ENG FROM C_HEAT_STATUS sc WHERE sc.HEAT_STATUS="C_HEAT_STATUS_ID") STATUS,
    "C_PLANT_UNIT_ID",
    (SELECT "PLANT_UNIT_CODE" FROM C_PLANT_UNIT cpu WHERE cpu.ID=C_PLANT_UNIT_ID
    ) AS "LAST_PLANT_UNIT",
    (SELECT "PLANT_UNIT_NO" FROM C_PLANT_UNIT cpu WHERE cpu.ID=C_PLANT_UNIT_ID
    ) AS "LAST_PLANT_UNIT_NO",
    (SELECT STEEL_GRADE FROM C_STEEL_GRADE CS WHERE CS.ID="C_STEEL_GRADE_ID"
    ) AS "STEEL_GRADE",
    "C_STEEL_GRADE_ID",
    "STEEL_WEIGHT",
    "SLAG_WEIGHT",
    "STEEL_TEMPERATURE"
     FROM PL_HEAT
  WHERE S_HEAT_ID IN (SELECT S_HEAT_ID FROM P_HEAT p WHERE p.C_HEAT_STATUS_ID IN (GET_HEAT_STATUS_ID(33),GET_HEAT_STATUS_ID(41)));
