--------------------------------------------------------
--  DDL for View VLH_REP_LADLE_ADD
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VLH_REP_LADLE_ADD" ("ID", "S_HEAT_ID", "HEAT_NO", "C_PLANT_UNIT_ID", "UNIT_NO", "UNIT_CODE", "C_MATERIAL_ID", "MAT_CODE", "MAT_WEIGHT", "DISCHARGE_TIME") AS 
  SELECT "ID",
    "S_HEAT_ID",
    (select HEAT_NO FROM S_HEAT s WHERE s.ID="S_HEAT_ID") as HEAT_NO,
    "C_PLANT_UNIT_ID",
    (SELECT PLANT_UNIT_NO FROM C_PLANT_UNIT cu WHERE cu.ID="C_PLANT_UNIT_ID") as UNIT_NO,
    (SELECT PLANT_UNIT_CODE FROM C_PLANT_UNIT cu WHERE cu.ID="C_PLANT_UNIT_ID") as UNIT_CODE,
    C_MATERIAL_ID,
    (SELECT "MAT_CODE" FROM C_MATERIAL cd WHERE cd.ID = "C_MATERIAL_ID") as "MAT_CODE",
    MAT_WEIGHT,
    DISCHARGE_TIME
  FROM P_MAT_REPORT;
