--------------------------------------------------------
--  DDL for View VLH_PM_HEAT_ANNOUNCE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VLH_PM_HEAT_ANNOUNCE" ("ID", "S_HEAT_ID", "HEAT_ID", "C_HEAT_STATUS_ID", "STATUS", "C_PLANT_UNIT_ID", "LAST_PLANT_UNIT", "LAST_PLANT_UNIT_NO", "STEEL_GRADE", "C_STEEL_GRADE_ID", "PRACTICE_CODE", "CL_PRACTICE_CODE_ID", "STEEL_WEIGHT", "SLAG_WEIGHT", "STEEL_TEMPERATURE", "TAP_TEMPERATURE") AS 
  SELECT "ID",
    "S_HEAT_ID",
    (SELECT HEAT_NO FROM S_HEAT WHERE ID="S_HEAT_ID"
    ) AS HEAT_ID,
    "C_HEAT_STATUS_ID",
    (SELECT HEAT_STATUS_DESC_ENG FROM C_HEAT_STATUS sc WHERE sc.ID=P.C_HEAT_STATUS_ID) as STATUS,
    (SELECT C_PLANT_UNIT_ID FROM PE_HEAT PE WHERE PE.S_HEAT_ID=P.S_HEAT_ID) AS "C_PLANT_UNIT_ID",
    (SELECT "PLANT_UNIT_CODE" FROM C_PLANT_UNIT cpu WHERE cpu.ID=(SELECT C_PLANT_UNIT_ID FROM PE_HEAT PE WHERE PE.S_HEAT_ID=P.S_HEAT_ID)
    ) AS "LAST_PLANT_UNIT",
    (SELECT "PLANT_UNIT_NO" FROM C_PLANT_UNIT cpu WHERE cpu.ID=p.last_plant_unit_id
    ) AS "LAST_PLANT_UNIT_NO",
    (SELECT STEEL_GRADE FROM C_STEEL_GRADE CS WHERE CS.ID="C_STEEL_GRADE_ID"
    ) AS "STEEL_GRADE",
    "C_STEEL_GRADE_ID",
    null AS "PRACTICE_CODE",
    null AS "CL_PRACTICE_CODE_ID",
    "STEEL_WEIGHT",
    "SLAG_WEIGHT",
    "STEEL_TEMP"  as "STEEL_TEMPERATURE",
    (SELECT TAP_TEMPERATURE FROM PE_HEAT PE WHERE PE.S_HEAT_ID=P."S_HEAT_ID"
    ) AS "TAP_TEMPERATURE"
     FROM P_HEAT P
  WHERE S_HEAT_ID IN
  (SELECT S_HEAT_ID FROM P_HEAT p WHERE p.C_HEAT_STATUS_ID IN (GET_HEAT_STATUS_ID(21)))
  union
    SELECT "ID",
    "S_HEAT_ID",
    (SELECT HEAT_NO FROM S_HEAT WHERE ID="S_HEAT_ID"
    ) AS HEAT_ID,
    "C_HEAT_STATUS_ID",
    (SELECT HEAT_STATUS_DESC_ENG FROM C_HEAT_STATUS sc WHERE sc.ID=P.C_HEAT_STATUS_ID) as STATUS,
    (SELECT C_PLANT_UNIT_ID FROM PL_HEAT PL WHERE PL.S_HEAT_ID=P.S_HEAT_ID AND pl.treat_no=(SELECT MAX(treat_no) from pl_heat where S_HEAT_ID=P.S_HEAT_ID)) AS "C_PLANT_UNIT_ID",
    (SELECT "PLANT_UNIT_CODE" FROM C_PLANT_UNIT cpu WHERE cpu.ID=(SELECT C_PLANT_UNIT_ID FROM PL_HEAT PL WHERE PL.S_HEAT_ID=P.S_HEAT_ID AND pl.treat_no=(SELECT MAX(treat_no) from pl_heat where S_HEAT_ID=P.S_HEAT_ID))
    ) AS "LAST_PLANT_UNIT",
    (SELECT "PLANT_UNIT_NO" FROM C_PLANT_UNIT cpu WHERE cpu.ID=p.last_plant_unit_id
    ) AS "LAST_PLANT_UNIT_NO",
    (SELECT STEEL_GRADE FROM C_STEEL_GRADE CS WHERE CS.ID="C_STEEL_GRADE_ID"
    ) AS "STEEL_GRADE",
    "C_STEEL_GRADE_ID",
    (SELECT PRACTICE_CODE FROM CL_PRACTICE WHERE ID=(SELECT pl.cl_practice_id FROM PL_HEAT PL WHERE PL.S_HEAT_ID=P.S_HEAT_ID AND pl.treat_no=(SELECT MAX(treat_no) from pl_heat where S_HEAT_ID=P.S_HEAT_ID))) AS "PRACTICE_CODE",
    (SELECT pl.cl_practice_id FROM PL_HEAT PL WHERE PL.S_HEAT_ID=P.S_HEAT_ID AND pl.treat_no=(SELECT MAX(treat_no) from pl_heat where S_HEAT_ID=P.S_HEAT_ID)) AS "CL_PRACTICE_CODE_ID",
    "STEEL_WEIGHT",
    "SLAG_WEIGHT",
    "STEEL_TEMP" as "STEEL_TEMPERATURE",
    (SELECT TAP_TEMPERATURE FROM PE_HEAT PE WHERE PE.S_HEAT_ID=P."S_HEAT_ID"
    ) AS "TAP_TEMPERATURE"
     FROM P_HEAT P
  WHERE S_HEAT_ID IN
  (SELECT S_HEAT_ID FROM P_HEAT p WHERE p.C_HEAT_STATUS_ID IN (GET_HEAT_STATUS_ID(33)))
  order by heat_id desc;
