--------------------------------------------------------
--  DDL for View VLH_HEATS_CONFIRM_ACT_LIST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VLH_HEATS_CONFIRM_ACT_LIST" ("S_HEAT_ID", "ACTIVITY", "ACTIVITY_TIME", "TEMPERATURE", "POWER_CONS") AS 
  select "S_HEAT_ID","ACTIVITY","ACTIVITY_TIME","TEMPERATURE","POWER_CONS" FROM
(
SELECT
S_HEAT_ID,
'Temp. Meas.' as ACTIVITY,
to_char(MEAS_TIME,'hh24:mi') AS ACTIVITY_TIME,
TEMPERATURE,
POWER_CONS
FROM P_TEMP_MEAS WHERE PLANT_UNIT='LF'
UNION
SELECT
S_HEAT_ID,
'Power On' as ACTIVITY,
to_char(decode(FIRST_POWER_ON_TIME, null, START_TIME+1/24/60*5, FIRST_POWER_ON_TIME),'hh24:mi') AS ACTIVITY_TIME,
0 as TEMPERATURE,
0 as POWER_CONS
FROM PL_HEAT
UNION
SELECT
S_HEAT_ID,
'Mat. Disch.' as ACTIVITY,
to_char(DISCHARGE_TIME,'hh24:mi') AS ACTIVITY_TIME,
0 as TEMPERATURE,
0 as POWER_CONS
FROM P_MAT_REPORT
)
ORDER BY ACTIVITY_TIME;
