--------------------------------------------------------
--  DDL for View VREP_QUICK_LIME
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_QUICK_LIME" ("DATE1", "SAMPLE_REC_TIME", "SAMPLE_NO", "Al2O3", "CAO", "MGO", "SIO", "P2O3", "REMARKS") AS 
  SELECT SAMPLE_TIME AS DATE1,
    SAMPLE_TIME      AS SAMPLE_REC_TIME,
    SAMPLE_ID        AS SAMPLE_NO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='AL2O3'
      )
    ) AS Al2O3, -- tady maji preklep asi - ma byt AL2O3
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='CAO'
      )
    ) AS CAO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='MGO'
      )
    ) AS MGO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='SIO2'
      )
    ) AS SIO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='P2O3'
      )
    ) AS P2O3,
    REMARK AS REMARKS
  FROM P_LAB_MAT p
  WHERE C_MATERIAL_ID IN
    (SELECT ID FROM C_MATERIAL WHERE UPPER(MAT_CODE) LIKE 'LIME0060'
    );
