--------------------------------------------------------
--  DDL for View VREP_RAW_MATERIAL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_RAW_MATERIAL" ("PRODUCTION_DATE", "SL_NO", "REPORT_NO", "SUPPLIER_NAME", "ITEMS_DESC", "TRUCK_NO", "LOI", "MOISTURE", "F_C", "SIZE_GM", "VM", "REMARKS", "AL2O3", "CAO", "MGO", "SIO", "ZRO", "CAF", "FEO", "TIO", "MNO", "CRO", "C_", "P2O3") AS 
  SELECT SAMPLE_TIME AS PRODUCTION_DATE,
    0                AS SL_NO,
    SAMPLE_ID        AS REPORT_NO,
    SUPPLIER_NAME    AS SUPPLIER_NAME,
    DESCRIPTION      AS ITEMS_DESC,
    TRUCK_NO         AS TRUCK_NO,
    0                AS LOI,
    0                AS MOISTURE,
    0                AS F_C,
    SIZE_GM_MT       AS SIZE_GM,
    0                AS VM,
    REMARK AS REMARKS,
    (
    SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='AL2O3'
      )
    ) AS AL2O3,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='CAO'
      )
    ) AS CAO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='MGO'
      )
    ) AS MGO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='SIO2'
      )
    ) AS SIO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='ZRO2'
      )
    ) AS ZRO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='CAF2'
      )
    ) AS CAF,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='FE2O3'
      )
    ) AS FEO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='TIO2'
      )
    ) AS TIO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='MNO'
      )
    ) AS MNO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='CR2O3'
      )
    ) AS CRO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='C'
      )
    ) AS C_,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='P2O3'
      )
    ) AS P2O3
  FROM P_LAB_MAT p
  WHERE C_MATERIAL_ID IN
    (SELECT ID FROM C_MATERIAL WHERE UPPER(MAT_CODE) LIKE 'SCRX%'
    );
