--------------------------------------------------------
--  DDL for View VREP_DAILY_DELAY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_DAILY_DELAY" ("S_NO", "HEAT_NO", "GRADE", "P_ONTIME", "TAP_TIME", "AGENCY", "START_TIME", "END_TIME", "TOTAL_TIME", "REASON_FDELAY") AS 
  SELECT
ROWNUM AS S_NO,
S_HEAT.HEAT_NO AS HEAT_NO,
C_STEEL_GRADE.STEEL_GRADE AS GRADE,
POWER_ON_TIME AS P_ONTIME,
TAP_START AS TAP_TIME,
C_DELAY.DELAY_CODE AS AGENCY,
P_DELAY.START_TIME AS START_TIME,
P_DELAY.END_TIME AS END_TIME,
(P_DELAY.END_TIME-P_DELAY.START_TIME)*24*60 AS TOTAL_TIME,
P_DELAY.USER_DESCR AS REASON_FDELAY
FROM
P_DELAY, S_HEAT, PE_HEAT, C_STEEL_GRADE, C_DELAY
WHERE
P_DELAY.S_HEAT_ID=S_HEAT.ID and
PE_HEAT.S_HEAT_ID=S_HEAT.ID and
PE_HEAT.C_STEEL_GRADE_ID = C_STEEL_GRADE.ID and
P_DELAY.DELAY_CODE_ID=C_DELAY.ID;
