--------------------------------------------------------
--  DDL for View VREP_METAL_LOSS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_METAL_LOSS" ("ID", "PRODUCTION_DATE", "S_HEAT_ID", "HEAT_NO", "L_SEQ", "DBAR_CUT", "TUNDISH_SKULL", "SHORT_LEN", "LADLE_SKULL", "SLAG_PIT", "BO", "LM_RTN", "SCALE_LOSS", "OXY", "TEMP", "SCALE_LOSS_CSP", "C") AS 
  SELECT
PML.ID AS "ID",
PH.END_TIME AS PRODUCTION_DATE,
PML."S_HEAT_ID" AS "S_HEAT_ID",
SH.HEAT_NO AS "HEAT_NO",
PML.L_SEQ AS "L_SEQ",
PML.DBAR_CUT AS "DBAR_CUT",
PML.TUNDISH_SKULL AS "TUNDISH_SKULL",
PML.SHORT_LEN AS "SHORT_LEN",
PML.LADLE_SKULL AS "LADLE_SKULL",
PML.SLAG_PIT AS "SLAG_PIT",
PML.BO AS "BO",
PML.LM_RTN AS "LM_RTN",
PML.SCALE_LOSS AS "SCALE_LOSS",
PML.OXY AS "OXY",
PML.TEMP AS "TEMP",
PML.SCALE_LOSS_CSP AS "SCALE_LOSS_CSP",
PML.C AS "C"
FROM P_METAL_LOSS PML,S_HEAT SH,P_HEAT PH
WHERE SH.ID = PML.S_HEAT_ID AND PH.S_HEAT_ID = PML.S_HEAT_ID;
