--------------------------------------------------------
--  DDL for View VREP_DAILY_DELAY_SUB2
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_DAILY_DELAY_SUB2" ("START_TIME", "COMMERCIAL", "CRANE", "CSP", "ELECTRICAL", "MECHANICAL", "OPERATION", "OTHERS", "O_PLANT", "POWER_FAILURE", "REFRACTORY", "TOTAL_DELAY") AS 
  SELECT
  START_TIME,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Commercial') ) AS COMMERCIAL,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Crane') ) AS CRANE,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='CSP') ) AS CSP,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Electrical') ) AS ELECTRICAL,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Mechanical') ) AS MECHANICAL,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Operation') ) AS OPERATION,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Others') ) AS OTHERS,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Oxygen_Pla') ) AS O_PLANT,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Power_Fail') ) AS POWER_FAILURE,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Refractory') ) AS REFRACTORY,
  (SELECT COUNT(1) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) ) AS TOTAL_DELAY
  FROM P_DELAY P;
