--------------------------------------------------------
--  DDL for View VREP_SLAG_SUB1
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_SLAG_SUB1" ("PRODUCTION_DATE", "SL_NO", "HEAT_NO", "SHIFT", "GRADE", "NAT_OF_SLAG", "CAO", "SIO", "MGO", "FEO", "SO", "ALO", "PO", "MNO", "TIO", "VO", "BASICITY") AS 
  SELECT p.TIME_ANALYSE AS PRODUCTION_DATE,
    p.SAMPLE_ID         AS SL_NO,
    s.HEAT_NO           AS HEAT_NO,
    '---'               AS SHIFT,
    '---'               AS GRADE,
    cp.PLANT_UNIT_CODE  AS NAT_OF_SLAG,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='CAO'
      )
    ) AS CAO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='SIO2'
      )
    ) AS SIO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='MGO'
      )
    ) AS MGO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='FEO'
      )
    ) AS FEO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='SO3'
      )
    ) AS SO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='AL2O3'
      )
    ) AS ALO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='P2O5'
      )
    ) AS PO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='MNO'
      )
    ) AS MNO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='TIO2'
      )
    ) AS TIO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA pa
    WHERE p.ID      =pa.P_LAB_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='V2O5'
      )
    ) AS VO,
    0 AS BASICITY
  FROM P_LAB p,
    P_LAB_ANA pa,
    S_HEAT s,
    C_PLANT_UNIT cp,
    C_PHASE cph
  WHERE p.S_HEAT_ID    =s.ID
  AND p.C_PLANT_UNIT_ID= cp.ID
  AND P.C_PHASE_ID     =cph.ID
  AND pa.P_LAB_ID     IN
    (SELECT ID FROM P_LAB WHERE C_SAMPLE_TYPE_ID=3
    );
