--------------------------------------------------------
--  DDL for View VREP_DAILY_DELAY_SUB1
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_DAILY_DELAY_SUB1" ("START_TIME", "ELECTRICAL", "MECHANICAL", "OPERATION", "POWER_FAILURE", "REFRACTORY", "COMMERCIAL", "CASATER", "CRANE", "CSP", "BLAST_FURNACE", "O_PLANT", "OTHERS", "TOTAL_DELAY", "PLANNED_SD") AS 
  SELECT
  START_TIME,
  (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Electrical') )*24*60 AS ELECTRICAL,
  (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Mechanical') )*24*60 AS MECHANICAL,
  (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Operation') )*24*60 AS OPERATION,
  (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Power_Fail') )*24*60 AS POWER_FAILURE,
  (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Refractory') )*24*60 AS REFRACTORY,
  (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Commercial') )*24*60 AS COMMERCIAL,
  (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Caster') )*24*60 AS CASTER,
 (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Crane') )*24*60 AS CRANE,
 (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='CSP') )*24*60 AS CSP,
 (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Blast_Furn') )*24*60 AS BLAST_FURNACE,
 (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Oxygen_Pla') )*24*60 AS O_PLANT,
(SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Others') )*24*60 AS OTHERS,
  (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) )*24*60 AS TOTAL_DELAY,
 (SELECT SUM(END_TIME-START_TIME) FROM P_DELAY pd WHERE TRUNC(START_TIME)=TRUNC(P.START_TIME) AND pd.DELAY_CODE_ID in (SELECT ID FROM C_DELAY WHERE DELAY_CODE='Planned_Sd') )*24*60 AS PLANNED_SD
FROM P_DELAY P;
