--------------------------------------------------------
--  DDL for View VREP_DAILYEAF_LADDETAILS_SUB2
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_DAILYEAF_LADDETAILS_SUB2" ("TOTAL_COST", "LANCING", "FREE_OPENING", "FREE_OPENING_2", "SUPPLIER") AS 
  SELECT
0 AS TOTAL_COST,
0 AS LANCING,
0 AS FREE_OPENING,
0 AS FREE_OPENING_2,
0 AS SUPPLIER
FROM DUAL;
