--------------------------------------------------------
--  DDL for View VREP_RAW_MATERIAL_SUB1
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VREP_RAW_MATERIAL_SUB1" ("PRODUCTION_DATE", "SL_NO", "REPORT_NO", "SUPPLIER_NAME", "ITEMS_DESC", "TRUCK_NO", "C_", "MN", "SI", "CA", "FE", "AL", "P", "S", "CR", "MO", "NI", "TI", "PB", "B", "NB", "SIZE_GM", "REMARKS") AS 
  SELECT SAMPLE_TIME AS PRODUCTION_DATE,
    0                AS SL_NO,
    SAMPLE_ID        AS REPORT_NO,
    SUPPLIER_NAME    AS SUPPLIER_NAME,
    DESCRIPTION      AS ITEMS_DESC,
    TRUCK_NO         AS TRUCK_NO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='C'
      )
    ) AS C,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='MN'
      )
    ) AS MN,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='SI'
      )
    ) AS SI,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='CA'
      )
    ) AS CA,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='FE'
      )
    ) AS FE,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='AL'
      )
    ) AS AL,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='P'
      )
    ) AS P,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='S'
      )
    ) AS S,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='CR'
      )
    ) AS CR,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='MO'
      )
    ) AS MO,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='NI'
      )
    ) AS NI,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='TI'
      )
    ) AS TI,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='PB'
      )
    ) AS PB,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='B'
      )
    ) AS B,
    (SELECT ELE_AMOUNT
    FROM P_LAB_ANA_MAT pa
    WHERE p.ID      =pa.P_LAB_MAT_ID
    AND C_ELEMENT_ID=
      (SELECT ID FROM C_ELEMENT WHERE UPPER(ELE_SYMBOL)='NB'
      )
    )          AS NB,
    SIZE_GM_MT AS SIZE_GM,
    REMARK AS REMARKS
  FROM P_LAB_MAT p
  WHERE C_MATERIAL_ID IN
    (SELECT ID FROM C_MATERIAL WHERE UPPER(MAT_CODE) LIKE 'SCRX%'
    );
