--------------------------------------------------------
--  DDL for View VVH_PM_ANA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VVH_PM_ANA" ("ELE_SYMBOL", "HMI_ORDER", "LAST_ANALYSIS", "MIN_GRADE", "MAX_GRADE", "AIM_GRADE", "MODEL_ANA") AS 
  SELECT
  ELE_SYMBOL,
  (SELECT HMI_ORDER FROM C_HMI_ELEMENT ch where CEL.ID = ch.C_ELEMENT_ID) as HMI_ORDER,
  (SELECT ELE_AMOUNT FROM P_LAB_ANA ANA WHERE ANA.C_ELEMENT_ID=CEL.ID AND ANA.P_LAB_ID=(SELECT max(ID) FROM P_LAB WHERE S_HEAT_ID = (SELECT S_HEAT_ID FROM VVH_PM_MAIN) )) LAST_ANALYSIS,
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA ANA WHERE ANA.C_ELEMENT_ID=CEL.ID AND ANA.C_STEEL_GRADE_ID=(SELECT C_STEEL_GRADE_ID FROM VVH_PM_MAIN )) MIN_GRADE,
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA ANA WHERE ANA.C_ELEMENT_ID=CEL.ID AND ANA.C_STEEL_GRADE_ID=(SELECT C_STEEL_GRADE_ID FROM VVH_PM_MAIN )) MAX_GRADE,
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA ANA WHERE ANA.C_ELEMENT_ID=CEL.ID AND ANA.C_STEEL_GRADE_ID=(SELECT C_STEEL_GRADE_ID FROM VVH_PM_MAIN )) AIM_GRADE,
  (SELECT ELE_AMOUNT FROM MV_HEAT_ANA ANA WHERE ANA.C_ELEMENT_ID=CEL.ID AND ANA.MV_HEAT_ID=(SELECT ID FROM MV_HEAT WHERE PV_HEAT_ID = (SELECT ID FROM PV_HEAT pl WHERE C_HEAT_STATUS_ID=GET_HEAT_STATUS_ID(40) AND pl.c_plant_unit_id=9) )) MODEL_ANA
from C_ELEMENT CEL;
