--------------------------------------------------------
--  DDL for View VVH_CHARGED_MATERIALS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VVH_CHARGED_MATERIALS" ("ID", "PHASE", "C_PLANT_UNIT_ID", "UNIT_CODE", "UNIT_NO", "BUNKER_NO", "C_MATERIAL_ID", "MAT_CODE", "MAT_REPORT_GROUP", "MAT_WEIGHT", "DISCHARGE_TIME", "S_HEAT_ID") AS 
  SELECT "ID",
     GET_VD_PHASE(S_HEAT_ID,DISCHARGE_TIME) as PHASE,
    "C_PLANT_UNIT_ID",
    "UNIT_CODE",
    "UNIT_NO",
    "BUNKER_NO",
    "C_MATERIAL_ID",
    "MAT_CODE",
    "MAT_REPORT_GROUP",
    "MAT_WEIGHT",
    "DISCHARGE_TIME",
    "S_HEAT_ID"
  FROM VGH_CHARGED_BUNKER_MAT
  WHERE UNIT_CODE='VD';
