--------------------------------------------------------
--  DDL for View VVH_HEAT_CONFIRMATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VVH_HEAT_CONFIRMATION" ("ID", "S_HEAT_ID", "HEAT_NO", "SHIFT", "DATE_PROD", "C_STEEL_GRADE_ID", "STEEL_GRADE", "SECTION", "LIQUIDUS_TEMP", "OPERATION_MODE", "LADLE_NO", "LADLE_LIFE", "PLUG_LIFE", "FREE_BOARD", "LIQUID_METAL", "LRF_TEMP", "LIFTING_TIME", "LIFTING_TEMP", "TEMP_TIPS", "SAMPLER", "BVD_TEMP", "AVD_TEMP", "AVD_SH_TEMP", "TEMP_DROP", "START_TIME", "END_TIME", "TOTAL_TIME", "RECEIVE_TIME", "PUMP_DOWN_TIME", "DEGASS_START_TIME", "BREAK_VACUUM_TIME", "TOTAL_DEGASS_TIME", "MIN_VACCUM", "STEAM_TEMP", "STEAM_PRESS", "COND_INLET_TEMP", "COND_OUTLET_TEMP", "ONE_MBAR_TIME", "CA_SI_WIRE_QUANTITY", "CA_FE_WIRE_QUANTITY", "S_WIRE_QUANTITY", "CA_SI_WIRE_TIME", "CA_FE_WIRE_TIME", "S_WIRE_TIME", "REMARK", "PLANT_UNIT_NO") AS 
  SELECT "ID",
    "S_HEAT_ID",
    (SELECT HEAT_NO FROM S_HEAT sh WHERE sh.ID="S_HEAT_ID") AS HEAT_NO,
    SHIFT,
    to_char(arrival, 'DD/MM/YY') as "DATE_PROD",
    C_STEEL_GRADE_ID,
    (SELECT STEEL_GRADE FROM C_STEEL_GRADE CS WHERE CS.ID="C_STEEL_GRADE_ID") AS "STEEL_GRADE",
    SECTION,
    (SELECT cs.liq_temp FROM C_STEEL_GRADE cs where cs.ID = pv_heat.c_steel_grade_id)LIQUIDUS_TEMP, -- from grade
    OPERATION_MODE,
    (SELECT EQUIPMENT_NO FROM C_EQUIPMENT CL WHERE CL.ID="C_EQUIPMENT_ID_LADLE"
    ) AS "LADLE_NO",
    0 LADLE_LIFE, -- from eq life tracking
    0 PLUG_LIFE, -- from eq life tracking
    FREE_BOARD,
    LIQUID_METAL,
    ARRIVAL_TEMP as LRF_TEMP,
    to_char(DEPARTURE, 'hh24:mi') as LIFTING_TIME,
    DEPARTURE_TEMP as LIFTING_TEMP,
    TEMP_TIPS,
    SAMPLER,
    BVD_TEMP,
    AVD_TEMP,
    (AVD_TEMP - (SELECT cs.liq_temp FROM C_STEEL_GRADE cs where cs.ID = pv_heat.c_steel_grade_id)) as AVD_SH_TEMP,
    BVD_TEMP - AVD_TEMP as TEMP_DROP,
    to_char("START_TIME", 'hh24:mi') START_TIME,
    to_char("END_TIME", 'hh24:mi') END_TIME,
    round(("END_TIME"-"START_TIME")/1*24*60*60) as TOTAL_TIME,
    to_char(ARRIVAL, 'hh24:mi') as RECEIVE_TIME,
    to_char(PUMP_DOWN_TIME, 'hh24:mi') as PUMP_DOWN_TIME,
    to_char(DEGASS_START_TIME, 'hh24:mi') DEGASS_START_TIME,
    to_char(BREAK_VACUUM_TIME, 'hh24:mi') BREAK_VACUUM_TIME,
    round((BREAK_VACUUM_TIME - DEGASS_START_TIME)/1*24*60*60) AS TOTAL_DEGASS_TIME,
    MIN_VACCUM,
    STEAM_TEMP,
    STEAM_PRESS,
    COND_INLET_TEMP,
    COND_OUTLET_TEMP,
    to_char(ONE_MBAR_TIME, 'hh24:mi') as ONE_MBAR_TIME,
    CA_SI_WIRE_QUANTITY,
    CA_FE_WIRE_QUANTITY,
    S_WIRE_QUANTITY,
    to_char(CA_SI_WIRE_TIME, 'hh24:mi') CA_SI_WIRE_TIME,
    to_char(CA_FE_WIRE_TIME, 'hh24:mi') CA_FE_WIRE_TIME,
    S_WIRE_TIME,
    VER_COMMENT as REMARK,
    1 as PLANT_UNIT_NO
  FROM PV_HEAT;
