--------------------------------------------------------
--  DDL for View VVH_STEEL_GRADE_ANA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VVH_STEEL_GRADE_ANA" ("C_STEEL_GRADE_ID", "STEEL_GRADE", "SPEC", "C", "Mn", "S", "P", "Si", "Al", "Ni", "Cr", "Mo", "Ti", "V", "N", "Ca") AS 
  SELECT
  "ID" AS C_STEEL_GRADE_ID,
  "STEEL_GRADE",
  'VD_MIN' as SPEC,
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "C",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Mn",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "S",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "P",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Si",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Al",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ni",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Cr",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Mo",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ti",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "V",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "N",
  (SELECT ELE_VD_MIN FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ca"
FROM C_STEEL_GRADE g
UNION
SELECT
  "ID" AS C_STEEL_GRADE_ID,
  "STEEL_GRADE",
  'VD_MAX' as SPEC,
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "C",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Mn",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "S",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "P",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Si",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Al",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ni",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Cr",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Mo",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ti",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "V",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "N",
  (SELECT ELE_VD_MAX FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ca"
FROM C_STEEL_GRADE g
UNION
SELECT
  "ID" AS C_STEEL_GRADE_ID,
  "STEEL_GRADE",
  'VD_AIM' as SPEC,
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "C",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Mn",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "S",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "P",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Si",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Al",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ni",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Cr",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Mo",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ti",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "V",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "N",
  (SELECT ELE_VD_AIM FROM C_STEEL_GRADE_ANA WHERE C_STEEL_GRADE_ID = g.ID AND C_ELEMENT_ID=(SELECT ID FROM C_ELEMENT WHERE ELE_SYMBOL='C' )) AS "Ca"
FROM C_STEEL_GRADE g;
