--------------------------------------------------------
--  DDL for View VVH_FIN_HEATS_CONFIRM
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VVH_FIN_HEATS_CONFIRM" ("ID", "S_HEAT_ID", "HEAT_ID", "STATUS", "LAST_PLANT_UNIT", "LAST_PLANT_UNIT_NO", "STEEL_GRADE", "TREAT_NO", "C_HEAT_STATUS_ID", "C_PLANT_UNIT_ID", "START_TIME", "END_TIME", "CV_PRACTICE_ID", "AIM_TEMP", "PHASE_SEQ_NO_CURR", "C_PHASE_ID", "C_STEEL_GRADE_ID", "LADLE_ID", "C_EQUIPMENT_ID_LADLE", "LADLE_POS", "VACUUM_TIME", "ARRIVAL", "ARRIVAL_TEMP", "DEPARTURE", "DEPARTURE_TEMP", "PUMP_DOWN_TIME", "DEGASS_START_TIME", "BREAK_VACUUM_TIME", "RETURN_HEAT_ID", "RETURN_WEIGHT", "STEEL_WEIGHT", "SLAG_WEIGHT", "STEEL_TEMPERATURE", "VERIFIED", "VER_COMMENT", "LADLE_STATE", "AR_CONS", "N2_CONS", "MIN_VACCUM", "STEAM_TEMP", "STEAM_PRESS", "COND_INLET_TEMP", "COND_OUTLET_TEMP", "ONE_MBAR_TIME", "SECTION", "LADLE_LIFE", "PLUG_LIFE", "FREE_BOARD", "LIQUID_METAL", "TEMP_TIPS", "SAMPLER", "BVD_TEMP", "AVD_TEMP", "AVD_SH_TEMP", "OPERATION_MODE", "LIQUIDUS_TEMP", "CA_SI_WIRE_QUANTITY", "CA_FE_WIRE_QUANTITY", "S_WIRE_QUANTITY", "CA_SI_WIRE_TIME", "CA_FE_WIRE_TIME", "S_WIRE_TIME", "CREATED", "MODIFIED", "MOP", "ACT_PRESSURE", "TARGET_PRESSURE") AS 
  SELECT "ID",
    "S_HEAT_ID",
    (SELECT HEAT_NO FROM S_HEAT WHERE ID="S_HEAT_ID"
    ) AS HEAT_ID,
    (SELECT HEAT_STATUS_DESC_ENG FROM C_HEAT_STATUS sc WHERE sc.HEAT_STATUS="C_HEAT_STATUS_ID") STATUS,
    (SELECT "PLANT_UNIT_CODE" FROM C_PLANT_UNIT cpu WHERE cpu.ID=C_PLANT_UNIT_ID
    ) AS "LAST_PLANT_UNIT",
    (SELECT "PLANT_UNIT_NO" FROM C_PLANT_UNIT cpu WHERE cpu.ID=C_PLANT_UNIT_ID
    ) AS "LAST_PLANT_UNIT_NO",
    (SELECT STEEL_GRADE FROM C_STEEL_GRADE CS WHERE CS.ID="C_STEEL_GRADE_ID"
    ) AS "STEEL_GRADE",
    "TREAT_NO",
    "C_HEAT_STATUS_ID",
    "C_PLANT_UNIT_ID",
    "START_TIME",
    "END_TIME",
    "CV_PRACTICE_ID",
    "AIM_TEMP",
    "PHASE_SEQ_NO_CURR",
    "C_PHASE_ID",
    "C_STEEL_GRADE_ID",
    (SELECT EQUIPMENT_NAME FROM C_EQUIPMENT CL WHERE CL.ID="C_EQUIPMENT_ID_LADLE"
    ) AS "LADLE_ID",
    "C_EQUIPMENT_ID_LADLE",
    "LADLE_POS",
    "VACUUM_TIME",
    "ARRIVAL",
    "ARRIVAL_TEMP",
    "DEPARTURE",
    "DEPARTURE_TEMP",
    "PUMP_DOWN_TIME",
    "DEGASS_START_TIME",
    "BREAK_VACUUM_TIME",
    "RETURN_HEAT_ID",
    "RETURN_WEIGHT",
    "STEEL_WEIGHT",
    "SLAG_WEIGHT",
    "STEEL_TEMPERATURE",
    "VERIFIED",
    "VER_COMMENT",
    "LADLE_STATE",
    "AR_CONS",
    "N2_CONS",
    "MIN_VACCUM",
    "STEAM_TEMP",
    "STEAM_PRESS",
    "COND_INLET_TEMP",
    "COND_OUTLET_TEMP",
    "ONE_MBAR_TIME",
    "SECTION",
    "LADLE_LIFE",
    "PLUG_LIFE",
    "FREE_BOARD",
    "LIQUID_METAL",
    "TEMP_TIPS",
    "SAMPLER",
    "BVD_TEMP",
    "AVD_TEMP",
    "AVD_SH_TEMP",
    "OPERATION_MODE",
    "LIQUIDUS_TEMP",
    "CA_SI_WIRE_QUANTITY",
    "CA_FE_WIRE_QUANTITY",
    "S_WIRE_QUANTITY",
    "CA_SI_WIRE_TIME",
    "CA_FE_WIRE_TIME",
    "S_WIRE_TIME",
    "CREATED",
    "MODIFIED",
    "MOP",
    "ACT_PRESSURE",
    "TARGET_PRESSURE"
  FROM PV_HEAT
  WHERE S_HEAT_ID IN
    (SELECT S_HEAT_ID
    FROM P_HEAT p
    WHERE p.C_HEAT_STATUS_ID IN (GET_HEAT_STATUS_ID(33),GET_HEAT_STATUS_ID(41))
    );
