--------------------------------------------------------
--  DDL for View VVH_PM_MATERIAL_SETP
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VVH_PM_MATERIAL_SETP" ("PHASE", "UNIT_CODE", "UNIT_NO", "BUNKER_NO", "MAT_CODE", "MAT_WEIGHT", "ADD_SEQ_NO") AS 
  SELECT
  'aa' as PHASE,
  'VD' UNIT_CODE,
  1 UNIT_NO,
  (SELECT BUNKER_NO FROM C_BUNKER B WHERE B.ID=C_BUNKER_ID) BUNKER_NO,
  (SELECT MAT_CODE FROM C_MATERIAL M WHERE M.ID=C_MATERIAL_ID) MAT_CODE,
  MAT_WEIGHT,
  ADD_SEQ_NO
FROM MV_MATERIAL_RECIPE MMR, MV_PRED_PHASE MPP
WHERE MMR.MV_PRED_PHASE_ID=MPP.ID;
