REM INSERTING into C_DELAY
SET DEFINE OFF;
Insert into C_DELAY (ID,DELAY_CODE,PLANT_UNIT_CODE,DELAY_DESC_ENG,DELAY_DESC_LOC,PLANT_EQUIP_NO,CREATED,MODIFIED,MOP) values (74722,'EAF_ELECT','EAF','P',null,null,to_date('2014-01-09 10:50:13','YYYY-MM-DD HH24:MI:SS'),to_date('2014-01-09 10:50:41','YYYY-MM-DD HH24:MI:SS'),'L2MS_HMI.vshost.exe');
Insert into C_DELAY (ID,DELAY_CODE,PLANT_UNIT_CODE,DELAY_DESC_ENG,DELAY_DESC_LOC,PLANT_EQUIP_NO,CREATED,MODIFIED,MOP) values (74721,'EAF_CRANE','EAF','Problem with crane',null,null,to_date('2014-01-09 09:44:27','YYYY-MM-DD HH24:MI:SS'),null,'L2MS_HMI.vshost.exe');
