REM INSERTING into C_HMI_PROFILE_RIGHT
SET DEFINE OFF;
Insert into C_HMI_PROFILE_RIGHT (ID,C_HMI_PROFILE_ID,C_HMI_DIALOG_ID,ACCESS_RIGHT,CREATED,MODIFIED,MOP) values (74521,1,1,1,to_date('2014-01-08 05:32:49','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
