REM INSERTING into C_HMI_REPORT
SET DEFINE OFF;
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74844,'QuickLimeReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.QuickLimeReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74845,'HmiFormatReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.HmiFormatReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74846,'DailyEAFLadleDetailsReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.DailyEAFLadleDetailsReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74847,'RawMaterialsReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.RawMaterialsReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74848,'LadleFinalReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.LadleFinalReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74849,'SlagReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.SlagReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74850,'MetallLossReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.MetallLossReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74851,'DailyProductionReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.DailyProductionReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74852,'FinalBloomReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.FinalBloomReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74853,'DailyDelayReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.DailyDelayReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74854,'DailyBloomProductionReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.DailyBloomProductionReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74855,'DoloLimeReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.DoloLimeReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_HMI_REPORT (ID,REP_NAME,REP_FILE,REP_CLASS,PLANT_UNIT_CODE,CREATED,MODIFIED,MOP) values (74856,'DailyProdDespatchReport','L2MS_HMI.exe','PTSW.L2.Visualization.Reports.DailyProdDespatchReport','GEN',to_date('2014-02-04 10:06:23','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
