REM INSERTING into C_MATERIAL_TAB
SET DEFINE OFF;
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (66964,'EAF_LOAD','Load materials for EAF',to_date('2014-01-06 11:11:12','YYYY-MM-DD HH24:MI:SS'),to_date('2014-01-06 04:26:29','YYYY-MM-DD HH24:MI:SS'),'SQL Developer');
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74499,'EAF_BASKET','Scrap materials in one basket',to_date('2014-01-06 04:26:54','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74503,'EAF_CONTI','Dri, lime, dololime',to_date('2014-01-06 04:37:10','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74507,'EAF_EN-8D','Tapping table for steel grade EN-19',to_date('2014-01-06 04:41:39','YYYY-MM-DD HH24:MI:SS'),to_date('2014-01-06 04:46:21','YYYY-MM-DD HH24:MI:SS'),'SQL Developer');
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74681,'EAF_HM','Dri, lime, dololime, hot metal',to_date('2014-01-06 04:41:39','YYYY-MM-DD HH24:MI:SS'),to_date('2014-01-06 04:46:21','YYYY-MM-DD HH24:MI:SS'),'SQL Developer');
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74691,'LF_START',null,null,null,null);
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74692,'LF_DEOX',null,null,null,null);
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74694,'LF_ALLOY',null,null,null,null);
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74696,'LF_ALU',null,null,null,null);
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74698,'LF_FINAL',null,null,null,null);
Insert into C_MATERIAL_TAB (ID,MAT_TAB_NAME,DESCRIPTION,CREATED,MODIFIED,MOP) values (74699,'LF_MAT_ADD',null,null,null,null);
