REM INSERTING into CC_COOLING_LIMIT
SET DEFINE OFF;
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,1,55,59,1500,37,52,40,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,2,55,61,1500,35,37,35,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,3,55,62,1500,35,45,30,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,4,56,59,1650,60,65,45,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,5,56,61,1650,55,60,40,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,6,56,62,1650,53,57,35,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,7,57,59,1725,62,68,45,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,8,57,61,1725,55,57,40,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,9,57,62,1725,53,54,35,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,10,58,59,1800,65,70,40,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,11,58,61,1800,57,62,37,null,null,null,null);
Insert into CC_COOLING_LIMIT (ID,CURVE_NO,CC_SECTION_DEF_ID,CC_C_CONTENT_DEF_ID,MCW,SR,ZONE_1,ZONE_2,DESCRIPTION,CREATED,MODIFIED,MOP) values (null,12,58,62,1800,48,52,35,null,null,null,null);
