REM INSERTING into CE_PRACT_ELECTRIC
SET DEFINE OFF;
Insert into CE_PRACT_ELECTRIC (ID,CE_PRACTICE_PHASE_ID,STEP_SEQ_NO,CE_EL_POWER_ID,STEP_TYPE,DURATION,STEP_SPECIFIC_ENERGY,STEP_ENERGY,CREATED,MODIFIED,MOP) values (24,10,1,83,0,60,null,null,null,null,null);
Insert into CE_PRACT_ELECTRIC (ID,CE_PRACTICE_PHASE_ID,STEP_SEQ_NO,CE_EL_POWER_ID,STEP_TYPE,DURATION,STEP_SPECIFIC_ENERGY,STEP_ENERGY,CREATED,MODIFIED,MOP) values (25,10,2,90,0,60,null,null,null,null,null);
Insert into CE_PRACT_ELECTRIC (ID,CE_PRACTICE_PHASE_ID,STEP_SEQ_NO,CE_EL_POWER_ID,STEP_TYPE,DURATION,STEP_SPECIFIC_ENERGY,STEP_ENERGY,CREATED,MODIFIED,MOP) values (26,10,3,93,1,null,null,null,null,null,null);
Insert into CE_PRACT_ELECTRIC (ID,CE_PRACTICE_PHASE_ID,STEP_SEQ_NO,CE_EL_POWER_ID,STEP_TYPE,DURATION,STEP_SPECIFIC_ENERGY,STEP_ENERGY,CREATED,MODIFIED,MOP) values (27,11,1,93,1,null,null,null,null,null,null);
Insert into CE_PRACT_ELECTRIC (ID,CE_PRACTICE_PHASE_ID,STEP_SEQ_NO,CE_EL_POWER_ID,STEP_TYPE,DURATION,STEP_SPECIFIC_ENERGY,STEP_ENERGY,CREATED,MODIFIED,MOP) values (28,12,1,93,1,null,null,null,null,null,null);
Insert into CE_PRACT_ELECTRIC (ID,CE_PRACTICE_PHASE_ID,STEP_SEQ_NO,CE_EL_POWER_ID,STEP_TYPE,DURATION,STEP_SPECIFIC_ENERGY,STEP_ENERGY,CREATED,MODIFIED,MOP) values (29,13,1,93,1,null,null,null,null,null,null);
