REM INSERTING into CE_PRACTICE
SET DEFINE OFF;
Insert into CE_PRACTICE (ID,PRACTICE_CODE,DESCRIPTION,NUM_OF_HOT_METAL,NUM_OF_BASKETS,CREATED,MODIFIED,MOP) values (1,'EAF_SCRAP_HM_DRI','EAF 1 basket, 1 hot metal, dri',1,1,to_date('2014-01-06 01:13:40','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
