REM INSERTING into CV_PRACTICE
SET DEFINE OFF;
Insert into CV_PRACTICE (ID,PRACTICE_CODE,DESCRIPTION,CREATED,MODIFIED,MOP) values (1,'VD_NORMAL','VD Standard practice',to_date('2014-03-24 16:01:20','YYYY-MM-DD HH24:MI:SS'),null,'SQL Developer');
