REM INSERTING into ML_PRED_ELECTRIC
SET DEFINE OFF;
Insert into ML_PRED_ELECTRIC (ID,PRED_PHASE_ID,STEP_SEQ_NO,CL_EL_POWER_ID,TYPE,DURATION,TEMPERATURE_DIFF,END_ENERGY,CREATED,MODIFIED,MOP) values (880,289,null,8,null,760,null,null,to_date('2014-04-28 10:09:25','YYYY-MM-DD HH24:MI:SS'),null,'MSL1.exe');
Insert into ML_PRED_ELECTRIC (ID,PRED_PHASE_ID,STEP_SEQ_NO,CL_EL_POWER_ID,TYPE,DURATION,TEMPERATURE_DIFF,END_ENERGY,CREATED,MODIFIED,MOP) values (3162,1535,null,8,null,760,null,null,to_date('2014-04-28 10:15:40','YYYY-MM-DD HH24:MI:SS'),null,'MSL1.exe');
Insert into ML_PRED_ELECTRIC (ID,PRED_PHASE_ID,STEP_SEQ_NO,CL_EL_POWER_ID,TYPE,DURATION,TEMPERATURE_DIFF,END_ENERGY,CREATED,MODIFIED,MOP) values (41,13,null,8,null,0,null,null,to_date('2014-04-28 09:45:27','YYYY-MM-DD HH24:MI:SS'),null,'MSL2.exe');
