REM INSERTING into P_METAL_LOSS
SET DEFINE OFF;
Insert into P_METAL_LOSS (ID,S_HEAT_ID,L_SEQ,DBAR_CUT,TUNDISH_SKULL,SHORT_LEN,LADLE_SKULL,SLAG_PIT,BO,LM_RTN,SCALE_LOSS,OXY,TEMP,SCALE_LOSS_CSP,C) values (161,4,'4',4,null,null,4,null,4,4,4,4,null,null,4);
Insert into P_METAL_LOSS (ID,S_HEAT_ID,L_SEQ,DBAR_CUT,TUNDISH_SKULL,SHORT_LEN,LADLE_SKULL,SLAG_PIT,BO,LM_RTN,SCALE_LOSS,OXY,TEMP,SCALE_LOSS_CSP,C) values (1,10,'3',3,3,3,4,3,3,5,3,3,3,3,3);
