REM INSERTING into PE_BLOW_REPORT
SET DEFINE OFF;
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (1,74634,'Oxygen',124,1541,1,21,null,null,null);
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (2,74634,'Nitrogen',50,4417,1,21,null,null,null);
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (3,74634,'Gas',35,447,1,21,null,null,null);
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (4,74635,'Oxygen',114,4454,1,21,null,null,null);
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (5,74635,'Gas',887,456,1,21,null,null,null);
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (6,74635,'Nitrogen',554,44,1,21,null,null,null);
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (7,74636,'Oxygen',546,4454,1,21,null,null,null);
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (8,74636,'Gas',5446,456,1,21,null,null,null);
Insert into PE_BLOW_REPORT (ID,C_EQUIP_ID,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,C_PLANT_UNIT_ID,S_HEAT_ID,CREATED,MODIFIED,MOP) values (9,74636,'Nitrogen',117,44,1,21,null,null,null);
