REM INSERTING into V_LF_PRACTICE2
SET DEFINE OFF;
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (1,8,1,0,8,0,23900,1,4);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,1,null,null,1,0,9940,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,2,null,null,2,0,1160,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,3,null,null,3,0,13130,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,4,null,null,4,0,15090,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,11,null,null,7,0,23900,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,6,null,null,6,0,19900,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,7,null,null,7,0,22400,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,9,null,null,5,0,19100,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,10,null,null,6,0,19500,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,0,null,null,0,0,0,null,null);
Insert into V_LF_PRACTICE2 (CLPE_ID,CLEP_ID,STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,ELECTRIC_POWER,IS_VARIABLE_STEP,CL_PRACTICE_PHASE_ID) values (null,5,null,null,5,0,17500,null,null);
