REM INSERTING into V_PLAN_OVERVIEW_ELECTRIC
SET DEFINE OFF;
Insert into V_PLAN_OVERVIEW_ELECTRIC (STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,END_ENERGY,S_HEAT_ID) values (1,60,11,2,811.7,42);
Insert into V_PLAN_OVERVIEW_ELECTRIC (STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,END_ENERGY,S_HEAT_ID) values (1,0,16,2,0,42);
Insert into V_PLAN_OVERVIEW_ELECTRIC (STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,END_ENERGY,S_HEAT_ID) values (1,34,16,2,658.9,42);
Insert into V_PLAN_OVERVIEW_ELECTRIC (STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,END_ENERGY,S_HEAT_ID) values (1,0,16,2,0,42);
Insert into V_PLAN_OVERVIEW_ELECTRIC (STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,END_ENERGY,S_HEAT_ID) values (2,59,14,2,987.3,42);
Insert into V_PLAN_OVERVIEW_ELECTRIC (STEP_SEQ_NO,DUR,VOLTAGE_TAP,TRANSFORMER_CURVE,END_ENERGY,S_HEAT_ID) values (3,946,16,2,17962.2,42);
