REM INSERTING into V_PLAN_OVERVIEW_OXYGEN
SET DEFINE OFF;
Insert into V_PLAN_OVERVIEW_OXYGEN (STEP_SEQ_NO,GAS_FLOW,DUR,GAS_AMOUNT,START_ENERGY,S_HEAT_ID) values (1,0.019444,0,0,0,42);
Insert into V_PLAN_OVERVIEW_OXYGEN (STEP_SEQ_NO,GAS_FLOW,DUR,GAS_AMOUNT,START_ENERGY,S_HEAT_ID) values (1,0.277778,0,0,0,42);
Insert into V_PLAN_OVERVIEW_OXYGEN (STEP_SEQ_NO,GAS_FLOW,DUR,GAS_AMOUNT,START_ENERGY,S_HEAT_ID) values (1,0.75,0,0,0,42);
Insert into V_PLAN_OVERVIEW_OXYGEN (STEP_SEQ_NO,GAS_FLOW,DUR,GAS_AMOUNT,START_ENERGY,S_HEAT_ID) values (1,0.75,0,0,0,42);
