REM INSERTING into V_PLAN_OVERVIEW_MATERIALS
SET DEFINE OFF;
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55615,'LIME0020');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55615,'LIME0020');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55615,'LIME0020');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55615,'LIME0020');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55616,'DOLO0020');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55659,'DRIP0010');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55616,'DOLO0020');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55616,'DOLO0020');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55659,'DRIP0010');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55659,'DRIP0010');
Insert into V_PLAN_OVERVIEW_MATERIALS (S_HEAT_ID,C_MATERIAL_ID,MATERIAL_CODE) values (42,55616,'DOLO0020');
