REM INSERTING into VCH_PRACTICE
SET DEFINE OFF;
Insert into VCH_PRACTICE (ID,PLANT_UNIT,PRACTICE_CODE,DESCRIPTION) values (1,'LF','LF_Normal',null);
Insert into VCH_PRACTICE (ID,PLANT_UNIT,PRACTICE_CODE,DESCRIPTION) values (1,'VD','VD_NORMAL','VD Standard practice');
