REM INSERTING into VEH_BASKET_STATUS
SET DEFINE OFF;
Insert into VEH_BASKET_STATUS (ID,BASKET_NO,BASKET_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75252,'Basket1','Basket 1','Loaded',50);
Insert into VEH_BASKET_STATUS (ID,BASKET_NO,BASKET_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75253,'Basket2','Basket 2','Empty',null);
Insert into VEH_BASKET_STATUS (ID,BASKET_NO,BASKET_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75254,'Basket3','Basket 3','Empty',null);
Insert into VEH_BASKET_STATUS (ID,BASKET_NO,BASKET_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75504,'Basket4','Basket 4','Empty',null);
