REM INSERTING into VEH_PM_BLOW_REPORT
SET DEFINE OFF;
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (1,1,'EAF',1,74634,null,'Oxygen',124,1541,21,null,null,null);
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (2,1,'EAF',1,74634,null,'Nitrogen',50,4417,21,null,null,null);
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (3,1,'EAF',1,74634,null,'Gas',35,447,21,null,null,null);
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (4,1,'EAF',1,74635,null,'Oxygen',114,4454,21,null,null,null);
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (5,1,'EAF',1,74635,null,'Gas',887,456,21,null,null,null);
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (6,1,'EAF',1,74635,null,'Nitrogen',554,44,21,null,null,null);
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (7,1,'EAF',1,74636,null,'Oxygen',546,4454,21,null,null,null);
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (8,1,'EAF',1,74636,null,'Gas',5446,456,21,null,null,null);
Insert into VEH_PM_BLOW_REPORT (ID,C_PLANT_UNIT_ID,UNIT_CODE,UNIT_NO,C_EQUIP_ID,C_EQUIP_NAME,BLOWN_MATERIAL,MAT_FLOW,MAT_AMOUNT,S_HEAT_ID,CREATED,MODIFIED,MOP) values (9,1,'EAF',1,74636,null,'Nitrogen',117,44,21,null,null,null);
