REM INSERTING into VEH_HM_STATUS
SET DEFINE OFF;
Insert into VEH_HM_STATUS (ID,LADLE_NO,LADLE_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75255,'HMLadle1',null,'Empty',null);
Insert into VEH_HM_STATUS (ID,LADLE_NO,LADLE_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75256,'HMLadle2',null,'Loaded',60);
Insert into VEH_HM_STATUS (ID,LADLE_NO,LADLE_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75257,'HMLadle4',null,'Empty',null);
Insert into VEH_HM_STATUS (ID,LADLE_NO,LADLE_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75258,'HMLadle3',null,'Empty',null);
Insert into VEH_HM_STATUS (ID,LADLE_NO,LADLE_DESC_ENG,STATUS,TOTAL_WEIGHT) values (75259,'HMLadle5',null,'Empty',null);
