REM INSERTING into VEH_PM_BASKET_DISCH
SET DEFINE OFF;
Insert into VEH_PM_BASKET_DISCH (C_EQUIPMENT_ID_BASKET,BASKET_NO,LAYER_SEQ_NO,C_MATERIAL_ID,MAT_CODE,MAT_WEIGHT,MAT_TEMPERATURE) values (75252,'Basket1',1,55664,'LQST0020',50,null);
