REM INSERTING into VEM_PRED_PHASES_MAT
SET DEFINE OFF;
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('LOAD',1,2,'LIME0020',498,722,6000,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('LOAD',1,3,'DOLO0020',498,602,5000,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('HOT_METAL',1,3,'DOLO0020',216,0,0,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('HOT_METAL',1,1,'DRIP0010',834,1706,23714,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('HOT_METAL',1,2,'LIME0020',216,0,0,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('DRI',1,3,'DOLO0020',0,0,0,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('DRI',1,1,'DRIP0010',0,0,0,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('DRI',1,2,'LIME0020',0,0,0,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('REFINING',1,3,'DOLO0020',0,0,0,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('REFINING',1,1,'DRIP0010',0,0,0,0);
Insert into VEM_PRED_PHASES_MAT (PHASE_TYPE,STEP_SEQ_NO,BUNKER_NO,MATERIAL_CODE,FEED_RATE,DURATION,MAT_WEIGHT,START_ENERGY) values ('REFINING',1,2,'LIME0020',0,0,0,0);
