REM INSERTING into VEM_HOT_METAL_ANA
SET DEFINE OFF;
Insert into VEM_HOT_METAL_ANA (ID,PE_HOT_METAL_ID,ELE_SYMBOL_ID,ELE_SYMBOL,ELE_AMOUNT) values (49,48,1,'C',0.045);
Insert into VEM_HOT_METAL_ANA (ID,PE_HOT_METAL_ID,ELE_SYMBOL_ID,ELE_SYMBOL,ELE_AMOUNT) values (50,48,2,'Mn',0.016);
Insert into VEM_HOT_METAL_ANA (ID,PE_HOT_METAL_ID,ELE_SYMBOL_ID,ELE_SYMBOL,ELE_AMOUNT) values (51,48,4,'P',0.002);
