REM INSERTING into VEM_PRED_PHASES_ENERGY
SET DEFINE OFF;
Insert into VEM_PRED_PHASES_ENERGY (PHASE_TYPE,STEP_SEQ_NO,REACTOR_TAP,VOLTAGE_TAP,ELECTRODE_CONTROL,DURATION,END_ENERGY) values ('SCRAP',1,5,11,2,60,811.7);
Insert into VEM_PRED_PHASES_ENERGY (PHASE_TYPE,STEP_SEQ_NO,REACTOR_TAP,VOLTAGE_TAP,ELECTRODE_CONTROL,DURATION,END_ENERGY) values ('SCRAP',2,5,14,2,59,987.3);
Insert into VEM_PRED_PHASES_ENERGY (PHASE_TYPE,STEP_SEQ_NO,REACTOR_TAP,VOLTAGE_TAP,ELECTRODE_CONTROL,DURATION,END_ENERGY) values ('SCRAP',3,5,16,2,946,17962.2);
Insert into VEM_PRED_PHASES_ENERGY (PHASE_TYPE,STEP_SEQ_NO,REACTOR_TAP,VOLTAGE_TAP,ELECTRODE_CONTROL,DURATION,END_ENERGY) values ('HOT_METAL',1,5,16,2,0,0);
Insert into VEM_PRED_PHASES_ENERGY (PHASE_TYPE,STEP_SEQ_NO,REACTOR_TAP,VOLTAGE_TAP,ELECTRODE_CONTROL,DURATION,END_ENERGY) values ('DRI',1,5,16,2,0,0);
Insert into VEM_PRED_PHASES_ENERGY (PHASE_TYPE,STEP_SEQ_NO,REACTOR_TAP,VOLTAGE_TAP,ELECTRODE_CONTROL,DURATION,END_ENERGY) values ('REFINING',1,5,16,2,34,658.9);
