REM INSERTING into VLH_PM_MATERIAL_SETP
SET DEFINE OFF;
Insert into VLH_PM_MATERIAL_SETP (PHASE,UNIT_CODE,UNIT_NO,BUNKER_NO,MAT_CODE,MAT_WEIGHT,ADD_SEQ_NO) values (null,'LF',1,5,'ALNP0010',297,null);
Insert into VLH_PM_MATERIAL_SETP (PHASE,UNIT_CODE,UNIT_NO,BUNKER_NO,MAT_CODE,MAT_WEIGHT,ADD_SEQ_NO) values (null,'LF',1,6,'FEMN0010',250,null);
Insert into VLH_PM_MATERIAL_SETP (PHASE,UNIT_CODE,UNIT_NO,BUNKER_NO,MAT_CODE,MAT_WEIGHT,ADD_SEQ_NO) values (null,'LF',1,8,'ANTR0010',107,null);
