REM INSERTING into VLH_HEATS_CONFIRM_ACT_LIST
SET DEFINE OFF;
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (21,'Power On','09:50',0,0);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (41,'Power On','10:12',0,0);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (41,'Power On','10:15',0,0);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (62,'Temp. Meas.','11:47',1523,null);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (62,'Temp. Meas.','11:47',1450,null);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (49,'Temp. Meas.','11:50',1510,null);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (48,'Temp. Meas.','12:08',1521,null);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (63,'Temp. Meas.','12:08',1451,null);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (63,'Temp. Meas.','12:09',1514,null);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (48,'Temp. Meas.','12:10',1454,null);
Insert into VLH_HEATS_CONFIRM_ACT_LIST (S_HEAT_ID,ACTIVITY,ACTIVITY_TIME,TEMPERATURE,POWER_CONS) values (48,'Temp. Meas.','12:21',1460,null);
