REM INSERTING into VLH_PM_HEAT_ANNOUNCE
SET DEFINE OFF;
Insert into VLH_PM_HEAT_ANNOUNCE (ID,S_HEAT_ID,HEAT_ID,C_HEAT_STATUS_ID,STATUS,C_PLANT_UNIT_ID,LAST_PLANT_UNIT,LAST_PLANT_UNIT_NO,STEEL_GRADE,C_STEEL_GRADE_ID,PRACTICE_CODE,CL_PRACTICE_CODE_ID,STEEL_WEIGHT,SLAG_WEIGHT,STEEL_TEMPERATURE,TAP_TEMPERATURE) values (141,63,null,55544,'EAF, heat treatment finished',1,'EAF',1,'EN-8D',1,null,null,null,null,null,null);
Insert into VLH_PM_HEAT_ANNOUNCE (ID,S_HEAT_ID,HEAT_ID,C_HEAT_STATUS_ID,STATUS,C_PLANT_UNIT_ID,LAST_PLANT_UNIT,LAST_PLANT_UNIT_NO,STEEL_GRADE,C_STEEL_GRADE_ID,PRACTICE_CODE,CL_PRACTICE_CODE_ID,STEEL_WEIGHT,SLAG_WEIGHT,STEEL_TEMPERATURE,TAP_TEMPERATURE) values (262,21,'13A0001',55548,'LF treatment finished',6,'LF',2,'EN-8D',1,'LF_Normal',1,90000,20000,1619,null);
