REM INSERTING into VLH_FIN_HEATS_CONFIRM
SET DEFINE OFF;
Insert into VLH_FIN_HEATS_CONFIRM (ID,S_HEAT_ID,HEAT_ID,C_HEAT_STATUS_ID,STATUS,C_PLANT_UNIT_ID,LAST_PLANT_UNIT,LAST_PLANT_UNIT_NO,STEEL_GRADE,C_STEEL_GRADE_ID,STEEL_WEIGHT,SLAG_WEIGHT,STEEL_TEMPERATURE) values (1,21,'13A0001',55548,null,6,'LF',2,'EN-8D',1,90000,20000,1619);
