REM INSERTING into VREP_DAILYEAF_LADDETAILS
SET DEFINE OFF;
Insert into VREP_DAILYEAF_LADDETAILS (EAF,SHELL_NO,HEAT_NO,BOTTOM,E1,E2,E3,DOOR,NOSE,EBT,ROOF,LF_ROOF,DPP_LIFE,CAMPAIGN,LAUNDER) values (1,'1',1,1,1,1,1,1,1,1,1,0,0,0,0);
Insert into VREP_DAILYEAF_LADDETAILS (EAF,SHELL_NO,HEAT_NO,BOTTOM,E1,E2,E3,DOOR,NOSE,EBT,ROOF,LF_ROOF,DPP_LIFE,CAMPAIGN,LAUNDER) values (2,'2',0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into VREP_DAILYEAF_LADDETAILS (EAF,SHELL_NO,HEAT_NO,BOTTOM,E1,E2,E3,DOOR,NOSE,EBT,ROOF,LF_ROOF,DPP_LIFE,CAMPAIGN,LAUNDER) values (3,'3',0,0,0,0,0,0,0,0,0,0,0,0,0);
Insert into VREP_DAILYEAF_LADDETAILS (EAF,SHELL_NO,HEAT_NO,BOTTOM,E1,E2,E3,DOOR,NOSE,EBT,ROOF,LF_ROOF,DPP_LIFE,CAMPAIGN,LAUNDER) values (4,'4',0,0,0,0,0,0,0,0,0,0,0,0,0);
