REM INSERTING into VREP_DAILY_DELAY_SUB2
SET DEFINE OFF;
Insert into VREP_DAILY_DELAY_SUB2 (START_TIME,COMMERCIAL,CRANE,CSP,ELECTRICAL,MECHANICAL,OPERATION,OTHERS,O_PLANT,POWER_FAILURE,REFRACTORY,TOTAL_DELAY) values (to_date('2014-01-14 10:09:11','YYYY-MM-DD HH24:MI:SS'),0,0,0,0,0,0,0,0,0,0,1);
