REM INSERTING into VREP_DAILY_BLOOM_PROD
SET DEFINE OFF;
Insert into VREP_DAILY_BLOOM_PROD (SL_NO,DATE1,SIZE1,GRADE,HEAT_NO,WEIGHT,STEEL_TYPE,REMARKS) values (0,to_date('2014-05-06 10:24:03','YYYY-MM-DD HH24:MI:SS'),'---','---','---',0,'---','---');
