REM INSERTING into VREP_DAILY_BLOOM_PROD_SUB1
SET DEFINE OFF;
Insert into VREP_DAILY_BLOOM_PROD_SUB1 (DESTINATION,GRADE,GRADE_GP,SIZE1,HEAT_NO,DATA1,DATA2,TOTAL1,TOTAL2,LORRIES) values ('---','---','---',0,'---','---','---',0,0,'---');
