REM INSERTING into VREP_DAILY_PRODUCTION_SUB1
SET DEFINE OFF;
Insert into VREP_DAILY_PRODUCTION_SUB1 (NO_OF_HEATS,BILLET_PRODUCTION,SLAB_PRODUCCTION,HR_PRODUCTION,AV_HSIZE_BS,LM_PRODUCTION,AV_HSIZE_LM,SCRAP_HM_DRI,LM_YIELD,LM_YIELD_CSP,EAF_POW_CONS,EAF_ELE_CONS) values ('---',0,0,0,0,0,0,'---',0,'---',0,0);
