--------------------------------------------------------
--  DDL for Table C_STEEL_GRADE
--------------------------------------------------------

  CREATE TABLE "C_STEEL_GRADE" 
   (	"ID" NUMBER, 
	"STEEL_GRADE" VARCHAR2(20 BYTE), 
	"DESCRIPTION_ENG" VARCHAR2(40 BYTE), 
	"DESCRIPTION_LOC" VARCHAR2(40 BYTE), 
	"GROUP_NAME" VARCHAR2(20 BYTE), 
	"CE_PRACTICE_ID" VARCHAR2(10 BYTE), 
	"CL_PRACTICE_ID" VARCHAR2(10 BYTE), 
	"CV_PRACTICE_ID" VARCHAR2(10 BYTE), 
	"CC_PRACTICE_ID" VARCHAR2(10 BYTE), 
	"AIM_TEMP_EAF" NUMBER(4,0) DEFAULT -1, 
	"AIM_TEMP_LF" NUMBER(4,0) DEFAULT -1, 
	"AIM_TEMP_LF_TO_VD" NUMBER(4,0) DEFAULT -1, 
	"AIM_TEMP_VD" NUMBER(4,0) DEFAULT -1, 
	"AIM_TEMP_CC" NUMBER(4,0) DEFAULT -1, 
	"FIRST_HEAT_TEMP_DIFF" NUMBER, 
	"SLAG_BASICITY_EAF" NUMBER(4,2), 
	"LIQ_TEMP" NUMBER(4,0) DEFAULT -1, 
	"DENSITY" NUMBER(4,0) DEFAULT -1, 
	"SOL_TEMP" NUMBER(4,0) DEFAULT -1, 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE), 
	"C_MATERIAL_TAB_ID" NUMBER
   ) ;

   COMMENT ON COLUMN "C_STEEL_GRADE"."STEEL_GRADE" IS 'steel grade identification';
   COMMENT ON COLUMN "C_STEEL_GRADE"."DESCRIPTION_ENG" IS 'english description';
   COMMENT ON COLUMN "C_STEEL_GRADE"."DESCRIPTION_LOC" IS 'local language description';
   COMMENT ON COLUMN "C_STEEL_GRADE"."CE_PRACTICE_ID" IS 'EAF production practice   ! CAN BE NULL - L3 does not send !';
   COMMENT ON COLUMN "C_STEEL_GRADE"."CL_PRACTICE_ID" IS 'LF production practice  ! CAN BE NULL - L3 does not send !';
   COMMENT ON COLUMN "C_STEEL_GRADE"."CV_PRACTICE_ID" IS 'VD production practice  ! CAN BE NULL - L3 does not send !';
   COMMENT ON COLUMN "C_STEEL_GRADE"."CC_PRACTICE_ID" IS 'CC production practice';
   COMMENT ON COLUMN "C_STEEL_GRADE"."AIM_TEMP_EAF" IS 'Unit [°C] : aim temperature for blowing';
   COMMENT ON COLUMN "C_STEEL_GRADE"."AIM_TEMP_LF" IS 'Unit [°C] : ';
   COMMENT ON COLUMN "C_STEEL_GRADE"."AIM_TEMP_LF_TO_VD" IS 'Unit [°C] : ';
   COMMENT ON COLUMN "C_STEEL_GRADE"."AIM_TEMP_VD" IS 'Unit [°C] : ';
   COMMENT ON COLUMN "C_STEEL_GRADE"."AIM_TEMP_CC" IS 'Unit [°C] : ';
   COMMENT ON COLUMN "C_STEEL_GRADE"."FIRST_HEAT_TEMP_DIFF" IS 'Unit [°C] : ';
   COMMENT ON COLUMN "C_STEEL_GRADE"."SLAG_BASICITY_EAF" IS 'Unit [-] : aim slag basicty at EAF';
   COMMENT ON COLUMN "C_STEEL_GRADE"."LIQ_TEMP" IS 'Unit [°C] : liquidus temperature';
   COMMENT ON COLUMN "C_STEEL_GRADE"."DENSITY" IS 'Unit [kg/m3] : ';
   COMMENT ON COLUMN "C_STEEL_GRADE"."SOL_TEMP" IS 'Unit [°C] : Solidus temperature';
   COMMENT ON COLUMN "C_STEEL_GRADE"."C_MATERIAL_TAB_ID" IS 'Tapping additions material table
';
