--------------------------------------------------------
--  DDL for Table C_WIRE_STRAND
--------------------------------------------------------

  CREATE TABLE "C_WIRE_STRAND" 
   (	"ID" NUMBER, 
	"C_PLANT_UNIT_ID" NUMBER, 
	"WIRE_FEEDER_NO" NUMBER DEFAULT 1, 
	"C_MATERIAL_ID" NUMBER, 
	"MAT_AVAILABLE_L1" NUMBER DEFAULT 1, 
	"MAT_AVAILABLE_L2" NUMBER DEFAULT 1, 
	"MAT_AMOUNT" NUMBER DEFAULT -1, 
	"MAX_FEED_RATE" FLOAT(126), 
	"MIN_FEED_RATE" FLOAT(126), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE), 
	"STRAND_NO" VARCHAR2(20 BYTE)
   ) ;
