--------------------------------------------------------
--  DDL for Table CC_PRACTICE
--------------------------------------------------------

  CREATE TABLE "CC_PRACTICE" 
   (	"ID" NUMBER, 
	"PRACTICE_CODE" VARCHAR2(10 BYTE), 
	"SPEED_OPT_LIM_TAB" NUMBER, 
	"SPEED_OPT_SHTEMP_TAB" NUMBER, 
	"SPEED_OPT_S_TAB" NUMBER, 
	"SPEED_OPT_MNS_TAB" NUMBER, 
	"SPEED_OPT_TWEIGHT_TAB" NUMBER, 
	"SPEED_OPT_CP_TAB" NUMBER, 
	"SPEED_OPT_TEMP_TAB" NUMBER, 
	"COOL_TAB" NUMBER, 
	"BP_TAB" NUMBER, 
	"SOLID_TAB" NUMBER, 
	"MOLDADJ_TAB" NUMBER, 
	"GEN_TAB" NUMBER, 
	"DSC_TEMP_TAB" NUMBER, 
	"MLC_TAB" NUMBER, 
	"HMO_TAB" NUMBER, 
	"HSA_TAB" NUMBER, 
	"TEMP_TAB" NUMBER, 
	"SLAB_COOL_TYPE" NUMBER, 
	"LIQUID_LENGTH_MIN" NUMBER, 
	"METALURGICAL_LENGTH_MAX" NUMBER, 
	"SURF_TEMP_UNBENDING_MIN" NUMBER, 
	"SURF_TEMP_UNBENDING_MAX" NUMBER, 
	"SURF_TEMP_END_CAGE_MIN" NUMBER, 
	"SURF_TEMP_END_CAGE_MAX" NUMBER, 
	"SURF_TEMP_SEGMENT_BAND" NUMBER, 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;

   COMMENT ON COLUMN "CC_PRACTICE"."PRACTICE_CODE" IS 'production practice identification';
   COMMENT ON COLUMN "CC_PRACTICE"."SLAB_COOL_TYPE" IS 'Slab cooling type, 0 - Air cooling, 1 - water cooling';
