--------------------------------------------------------
--  DDL for Table CE_PRACT_INJECTION
--------------------------------------------------------

  CREATE TABLE "CE_PRACT_INJECTION" 
   (	"ID" NUMBER, 
	"CE_PRACTICE_PHASE_ID" NUMBER, 
	"STEP_SEQ_NO" NUMBER, 
	"CE_INJECTION_TYPE_ID" NUMBER, 
	"DEVICE_NO" NUMBER, 
	"STEP_TYPE" NUMBER DEFAULT 0, 
	"SCHED_FLOW" NUMBER, 
	"MIN_FLOW" NUMBER, 
	"AMOUNT" NUMBER, 
	"DURATION" NUMBER, 
	"START_SPECIFIC_ENERGY" NUMBER, 
	"START_ENERGY" NUMBER, 
	"DEVICE_POSITION" NUMBER, 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;

   COMMENT ON COLUMN "CE_PRACT_INJECTION"."CE_PRACTICE_PHASE_ID" IS 'Reference to CE_PRACTICE table';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."STEP_SEQ_NO" IS 'practice step identification';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."CE_INJECTION_TYPE_ID" IS 'rcb, ebt, top, door, etc…';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."DEVICE_NO" IS 'number of device';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."STEP_TYPE" IS '0 = fixed step, 1 = variable step';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."SCHED_FLOW" IS 'Unit [Nm3/s] : ';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."MIN_FLOW" IS 'Unit [Nm3/s] : ';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."AMOUNT" IS 'Unit [Nm3] : ';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."DURATION" IS 'Unit [s] : ';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."START_SPECIFIC_ENERGY" IS 'Unit [kWh/kg] : specific energy consumed up to step start';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."START_ENERGY" IS 'Start el. energy kWh';
   COMMENT ON COLUMN "CE_PRACT_INJECTION"."DEVICE_POSITION" IS 'Unit [mm] : device position';
