--------------------------------------------------------
--  DDL for Table M_ADAPTATION
--------------------------------------------------------

  CREATE TABLE "M_ADAPTATION" 
   (	"ID" NUMBER, 
	"PLANT_UNIT_ID" NUMBER, 
	"S_HEAT_ID" NUMBER, 
	"STEEL_GRADE_ID" NUMBER, 
	"MEASURED_TIME" DATE, 
	"PHASE_SEQ_NO_ID" NUMBER, 
	"TEMP_START" NUMBER(8,4), 
	"TEMP_END" NUMBER(8,4), 
	"TEMP_CALC" NUMBER(8,4), 
	"TEMP_ENERGY" NUMBER(8,4), 
	"TEMP_ENERGY_CALC" NUMBER(8,4), 
	"STEEL_WEIGHT_START" NUMBER(8,0), 
	"STEEL_WEIGHT_END" NUMBER(8,0), 
	"SLAG_WEIGHT_START" NUMBER(8,0), 
	"SLAG_WEIGHT_END" NUMBER(8,0), 
	"EXCLUDE_FR_CALC" NUMBER, 
	"LADLE_STATE" NUMBER, 
	"LOSS_TIME" NUMBER(8,0), 
	"ENERGY_INDX0" NUMBER(8,4), 
	"ENERGY_INDX1" NUMBER(8,4), 
	"ENERGY_INDX2" NUMBER(8,4), 
	"ENERGY_INDX3" NUMBER(8,4), 
	"ENERGY_INDX4" NUMBER(8,4), 
	"ENERGY_INDX5" NUMBER(8,4), 
	"ENERGY_INDX6" NUMBER(8,4), 
	"ENERGY_INDX7" NUMBER(8,4), 
	"ENERGY_INDX8" NUMBER(8,4), 
	"ENERGY_INDX9" NUMBER(8,4), 
	"ENERGY_INDX10" NUMBER(8,4), 
	"ENERGY_INDX11" NUMBER(8,4), 
	"ENERGY_INDX12" NUMBER(8,4), 
	"ENERGY_INDX13" NUMBER(8,4), 
	"ENERGY_INDX14" NUMBER(8,4), 
	"ENERGY_INDX15" NUMBER(8,4), 
	"ENERGY_INDX16" NUMBER(8,4), 
	"ENERGY_INDX17" NUMBER(8,4), 
	"ENERGY_INDX18" NUMBER(8,4), 
	"ENERGY_INDX19" NUMBER(8,4), 
	"MAT_CODE_INDX0" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX1" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX2" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX3" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX4" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX5" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX6" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX7" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX8" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX9" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX10" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX11" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX12" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX13" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX14" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX15" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX16" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX17" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX18" VARCHAR2(20 BYTE), 
	"MAT_CODE_INDX19" VARCHAR2(20 BYTE), 
	"MAT_ENERGY_INDX0" NUMBER(8,4), 
	"MAT_ENERGY_INDX1" NUMBER(8,4), 
	"MAT_ENERGY_INDX2" NUMBER(8,4), 
	"MAT_ENERGY_INDX3" NUMBER(8,4), 
	"MAT_ENERGY_INDX4" NUMBER(8,4), 
	"MAT_ENERGY_INDX5" NUMBER(8,4), 
	"MAT_ENERGY_INDX6" NUMBER(8,4), 
	"MAT_ENERGY_INDX7" NUMBER(8,4), 
	"MAT_ENERGY_INDX8" NUMBER(8,4), 
	"MAT_ENERGY_INDX9" NUMBER(8,4), 
	"MAT_ENERGY_INDX10" NUMBER(8,4), 
	"MAT_ENERGY_INDX11" NUMBER(8,4), 
	"MAT_ENERGY_INDX12" NUMBER(8,4), 
	"MAT_ENERGY_INDX13" NUMBER(8,4), 
	"MAT_ENERGY_INDX14" NUMBER(8,4), 
	"MAT_ENERGY_INDX15" NUMBER(8,4), 
	"MAT_ENERGY_INDX16" NUMBER(8,4), 
	"MAT_ENERGY_INDX17" NUMBER(8,4), 
	"MAT_ENERGY_INDX18" NUMBER(8,4), 
	"MAT_ENERGY_INDX19" NUMBER(8,4), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;

   COMMENT ON COLUMN "M_ADAPTATION"."PLANT_UNIT_ID" IS 'plant unit number - 1,2';
   COMMENT ON COLUMN "M_ADAPTATION"."S_HEAT_ID" IS 'heat identification';
   COMMENT ON COLUMN "M_ADAPTATION"."STEEL_GRADE_ID" IS 'steel grade';
   COMMENT ON COLUMN "M_ADAPTATION"."MEASURED_TIME" IS 'time of the measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."TEMP_START" IS 'Unit [°C] : temperature at previous temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."TEMP_END" IS 'Unit [°C] : temperature at current temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."TEMP_CALC" IS 'Unit [°C] : temperature calculated at time of current temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."TEMP_ENERGY" IS 'Unit [kWh] : temperature calculated at time of current temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."TEMP_ENERGY_CALC" IS 'Unit [kWh] : temperature calculated at time of current temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."STEEL_WEIGHT_START" IS 'Unit [kg] : steel weight at previous temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."STEEL_WEIGHT_END" IS 'Unit [kg] : steel weight at current temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."SLAG_WEIGHT_START" IS 'Unit [kg] : slag weight at previous temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."SLAG_WEIGHT_END" IS 'Unit [kg] : slag weight at current temperature measurement';
   COMMENT ON COLUMN "M_ADAPTATION"."EXCLUDE_FR_CALC" IS 'Exclude from calculation flag';
   COMMENT ON COLUMN "M_ADAPTATION"."LADLE_STATE" IS 'state of the ladle (hot=0, medium=1, cold=2)';
   COMMENT ON COLUMN "M_ADAPTATION"."LOSS_TIME" IS 'Unit [s] : time between two measurments of temperature';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX0" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX1" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX2" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX3" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX4" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX5" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX6" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX7" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX8" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX9" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX10" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX11" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX12" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX13" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX14" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX15" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX16" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX17" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX18" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."ENERGY_INDX19" IS 'Unit [kWh] : energy array, description in M_ADAPT_DESC';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX0" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX1" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX2" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX3" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX4" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX5" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX6" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX7" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX8" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX9" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX10" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX11" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX12" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX13" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX14" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX15" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX16" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX17" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX18" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_CODE_INDX19" IS 'material code';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX0" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX1" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX2" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX3" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX4" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX5" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX6" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX7" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX8" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX9" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX10" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX11" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX12" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX13" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX14" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX15" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX16" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX17" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX18" IS 'Unit [kWh] : material energy';
   COMMENT ON COLUMN "M_ADAPTATION"."MAT_ENERGY_INDX19" IS 'Unit [kWh] : material energy';
