--------------------------------------------------------
--  DDL for Table MC_CSO_OBSERVATION_STRAND
--------------------------------------------------------

  CREATE TABLE "MC_CSO_OBSERVATION_STRAND" 
   (	"ID" NUMBER, 
	"STRAND_NO" NUMBER, 
	"CURRENT_SPEED" NUMBER(14,11) DEFAULT 0, 
	"SETP_SPEED" NUMBER(14,11) DEFAULT 0, 
	"CAST_WIDTH" NUMBER DEFAULT 0, 
	"CAST_THICKNESS" NUMBER DEFAULT 0, 
	"HF_NFL" NUMBER(14,8) DEFAULT 0, 
	"HF_NFR" NUMBER(14,8) DEFAULT 0, 
	"HF_LS" NUMBER(14,8) DEFAULT 0, 
	"HF_FS" NUMBER(14,8) DEFAULT 0, 
	"ACT_TAPER_LEFT" NUMBER DEFAULT 0, 
	"ACT_TAPER_RIGHT" NUMBER DEFAULT 0, 
	"PRESET_TAPER_LEFT" NUMBER DEFAULT 0, 
	"PRESET_TAPER_RIGHT" NUMBER DEFAULT 0, 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;

   COMMENT ON COLUMN "MC_CSO_OBSERVATION_STRAND"."STRAND_NO" IS 'strand number';
   COMMENT ON COLUMN "MC_CSO_OBSERVATION_STRAND"."CURRENT_SPEED" IS 'Current speed';
   COMMENT ON COLUMN "MC_CSO_OBSERVATION_STRAND"."SETP_SPEED" IS 'speed setpoint';
