--------------------------------------------------------
--  DDL for Table ME_ALLOY_ANA
--------------------------------------------------------

  CREATE TABLE "ME_ALLOY_ANA" 
   (	"ID" NUMBER, 
	"PRED_PHASE_ID" NUMBER, 
	"SAMPLE_NO" NUMBER, 
	"ELE_AMOUNT_ARR_INDX0" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX1" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX2" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX3" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX4" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX5" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX6" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX7" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX8" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX9" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX10" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX11" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX12" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX13" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX14" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX15" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX16" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX17" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX18" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX19" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX20" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX21" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX22" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX23" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX24" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX25" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX26" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX27" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX28" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX29" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX30" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX31" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX32" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX33" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX34" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX35" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX36" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX37" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX38" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX39" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX40" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX41" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX42" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX43" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX44" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX45" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX46" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX47" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX48" NUMBER(14,11) DEFAULT -1, 
	"ELE_AMOUNT_ARR_INDX49" NUMBER(14,11) DEFAULT -1, 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;

   COMMENT ON COLUMN "ME_ALLOY_ANA"."PRED_PHASE_ID" IS 'reference to ME_PRED_PHASE table';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."SAMPLE_NO" IS 'identification of the steel sample the calculation was based on - see tab. P_LAB_ANA';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX0" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX1" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX2" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX3" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX4" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX5" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX6" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX7" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX8" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX9" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX10" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX11" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX12" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX13" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX14" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX15" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX16" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX17" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX18" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX19" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX20" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX21" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX22" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX23" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX24" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX25" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX26" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX27" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX28" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX29" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX30" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX31" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX32" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX33" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX34" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX35" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX36" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX37" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX38" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX39" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX40" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX41" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX42" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX43" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX44" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX45" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX46" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX47" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX48" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
   COMMENT ON COLUMN "ME_ALLOY_ANA"."ELE_AMOUNT_ARR_INDX49" IS 'Unit [kg/kg] : relative element amount  = ELE_AMOUNT_ARR [  ELE_ARRAY_IDX from C_ELEMENT ]';
