--------------------------------------------------------
--  DDL for Table ME_HEAT_HIST
--------------------------------------------------------

  CREATE TABLE "ME_HEAT_HIST" 
   (	"ID" NUMBER, 
	"S_HEAT_ID" NUMBER, 
	"CHARGE_WEIGHT" NUMBER(8,0), 
	"STEEL_WEIGHT" NUMBER(8,0), 
	"SLAG_WEIGHT" NUMBER(8,0), 
	"CURR_PHASE_SEQ_NO" NUMBER, 
	"CURR_PHASE_TYPE_ID" NUMBER, 
	"CHARGE_MAT_ENERGY" NUMBER(12,1), 
	"SPECIFIC_ENERGY" NUMBER(12,1), 
	"ENERGY_LOSS_SUMM" NUMBER(12,1), 
	"CALCUL_TEMPERATURE" NUMBER(4,0), 
	"LANCE_C" NUMBER, 
	"DRI_WEIGHT" NUMBER, 
	"LIME_WEIGHT" NUMBER, 
	"DOLO_WEIGHT" NUMBER, 
	"SPEC_WEIGHT" NUMBER, 
	"LANCE_O_EBT" NUMBER, 
	"LANCE_C_EBT" NUMBER, 
	"COOLING_LOSS" NUMBER(12,4), 
	"ROOF_COOLING_LOSS" NUMBER(12,4), 
	"GENERAL_LOSS" NUMBER(12,4), 
	"ROOF_LOSS" NUMBER(12,4), 
	"EXOTHERM_ENERGY" NUMBER(12,4), 
	"ENDOTHERM_ENERGY" NUMBER(12,4), 
	"DURATION" NUMBER(6,0), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;
