--------------------------------------------------------
--  DDL for Table P_CASTER_STATUS
--------------------------------------------------------

  CREATE TABLE "P_CASTER_STATUS" 
   (	"ID" NUMBER, 
	"PLANT_UNIT" VARCHAR2(3 BYTE), 
	"PLANT_UNIT_NO" NUMBER(1,0), 
	"HEAT_ID" VARCHAR2(10 BYTE), 
	"HEAT_STATUS_ID" NUMBER, 
	"LADLE_NO" NUMBER(2,0), 
	"REMAINING_LADLE_WEIGHT" NUMBER(5,2), 
	"STEEL_GRADE" VARCHAR2(20 BYTE), 
	"REMAINING_LADLE_TIME" NUMBER(5,0), 
	"CASTING_SPEED_STR1" NUMBER(3,2), 
	"CASTING_SPEED_STR2" NUMBER(3,2), 
	"CASTING_SPEED_STR3" NUMBER(3,2), 
	"CASTING_SPEED_STR4" NUMBER(3,2), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE), 
	"TUNDISH_TEMPERATURE" NUMBER
   ) ;
