--------------------------------------------------------
--  DDL for Table PC_HEAT_STRAND
--------------------------------------------------------

  CREATE TABLE "PC_HEAT_STRAND" 
   (	"ID" NUMBER, 
	"S_HEAT_ID" NUMBER, 
	"STRAND_NO" NUMBER, 
	"CAST_START_TIME" DATE, 
	"CAST_START_WEIGHT" NUMBER, 
	"CAST_START_TUND_WEIGHT" NUMBER, 
	"CAST_START_CAST_LEN" FLOAT(126), 
	"CAST_START_CAST_SPEED" NUMBER(6,4), 
	"CAST_END_TIME" DATE, 
	"CAST_END_WEIGHT" NUMBER, 
	"CAST_END_TUND_WEIGHT" NUMBER, 
	"CAST_END_CAST_LEN" FLOAT(126), 
	"CAST_END_CAST_SPEED" NUMBER(6,4), 
	"CAST_POWDER_TYPE" NUMBER, 
	"CAST_POWDER_LOT" NUMBER, 
	"CAST_POWDER_AMOUNT" NUMBER, 
	"SEC_COOLING_PERC" NUMBER, 
	"DUMMY_BAR_START" DATE, 
	"DUMMY_BAR_END" DATE, 
	"MOULD_PREP_START" DATE, 
	"MOULD_PREP_END" DATE, 
	"TAILOUT_START" DATE, 
	"TAILOUT_END" DATE, 
	"LADLE_OPEN_CAST_LEN" FLOAT(126), 
	"LADLE_OPEN_CAST_SPEED" NUMBER(6,4), 
	"LADLE_CLOSE_CAST_LEN" FLOAT(126), 
	"LADLE_CLOSE_CAST_SPEED" NUMBER(6,4), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;

   COMMENT ON COLUMN "PC_HEAT_STRAND"."S_HEAT_ID" IS 'heat identification';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_START_TIME" IS 'New heat in mold time';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_START_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_START_TUND_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_START_CAST_LEN" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_START_CAST_SPEED" IS 'Unit [m/s] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_END_TIME" IS 'Last slab cut time';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_END_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_END_TUND_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_END_CAST_LEN" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_END_CAST_SPEED" IS 'Unit [m/s] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."CAST_POWDER_AMOUNT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."SEC_COOLING_PERC" IS 'Unit [%] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."DUMMY_BAR_START" IS 'Dummy bar insert start time (only for first heat in seq)';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."DUMMY_BAR_END" IS 'Dummy bar insert end time (only for first heat in seq)';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."MOULD_PREP_START" IS 'Mould preparation start time';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."MOULD_PREP_END" IS 'Mould preparation end time';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."TAILOUT_START" IS 'Tailout start time  (only for last heat in seq)';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."TAILOUT_END" IS 'Tailout end time  (only for last heat in seq)';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."LADLE_OPEN_CAST_LEN" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."LADLE_OPEN_CAST_SPEED" IS 'Unit [m/s] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."LADLE_CLOSE_CAST_LEN" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_HEAT_STRAND"."LADLE_CLOSE_CAST_SPEED" IS 'Unit [m/s] : ';
