--------------------------------------------------------
--  DDL for Table PC_MOULD_CONTROL
--------------------------------------------------------

  CREATE TABLE "PC_MOULD_CONTROL" 
   (	"ID" NUMBER, 
	"STRAND_NO" NUMBER, 
	"LEVEL_ACT" FLOAT(126), 
	"LEVEL_SETPOINT" FLOAT(126), 
	"LEVEL_AVG" FLOAT(126), 
	"LEVEL_MAX" FLOAT(126), 
	"LEVEL_MIN" FLOAT(126), 
	"LEVEL_STDEV" FLOAT(126), 
	"LEVEL_SETPOINT_MODE" NUMBER, 
	"LEVEL_CONTROL_MODE" NUMBER, 
	"LEVEL_MEAS_STATUS" NUMBER, 
	"LEVEL_MEAS_READY" NUMBER, 
	"STOPPER_SHUT_DOWN" NUMBER, 
	"HYDR_EMERGENCY_STATUS" NUMBER, 
	"HYDR_PUMP_START_TC1" NUMBER, 
	"HYDR_PUMP_FAULT_TC1" NUMBER, 
	"STOPPER_POS_SIGNAL_FAULT_TC1" NUMBER, 
	"OIL_TEMP_MIN_TC1" NUMBER, 
	"OIL_TEMP_MAX_TC1" NUMBER, 
	"OIL_LEVEL_MIN_TC1" NUMBER, 
	"PRESSURE_FAULT_TC1" NUMBER, 
	"FILTER_CLOGGED_TC1" NUMBER, 
	"HYDR_PUMP_START_TC2" NUMBER, 
	"HYDR_PUMP_FAULT_TC2" NUMBER, 
	"STOPPER_POS_SIGNAL_FAULT_TC2" NUMBER, 
	"OIL_TEMP_MIN_TC2" NUMBER, 
	"OIL_TEMP_MAX_TC2" NUMBER, 
	"OIL_LEVEL_MIN_TC2" NUMBER, 
	"PRESSURE_FAULT_TC2" NUMBER, 
	"FILTER_CLOGGED_TC2" NUMBER, 
	"HYDR_STATUS" NUMBER, 
	"ACOUSTIC_ALARM" NUMBER, 
	"LEVEL_MIN_ALARM" NUMBER, 
	"LEVEL_MAX_ALARM" NUMBER, 
	"FULL_CALIB_STATUS" NUMBER, 
	"EMPTY_CALIB_STATUS" NUMBER, 
	"AIM_MOULD_LEVEL" FLOAT(126), 
	"ACTIVE_CAR_NO" FLOAT(126), 
	"STOPPER_OPEN_POS" FLOAT(126), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;

   COMMENT ON COLUMN "PC_MOULD_CONTROL"."STRAND_NO" IS 'Strand number';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_ACT" IS 'Level Actual Value';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_SETPOINT" IS 'Level Set Point Value';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_AVG" IS 'Actual Level Average Value';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_MAX" IS 'Level Minimum Value';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_MIN" IS 'Level Maximum Value';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_STDEV" IS 'Level Standard Deviation';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_SETPOINT_MODE" IS 'Level Set Point Mode (0 - Computer / 1 - Panel)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_CONTROL_MODE" IS 'Level Control Mode (0 - Manual / 1 - Automatic)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_MEAS_STATUS" IS 'MLC System ready (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_MEAS_READY" IS 'MLC Measurement Device Fault (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."STOPPER_SHUT_DOWN" IS 'Stopper Shut Down (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."HYDR_EMERGENCY_STATUS" IS 'Hydraulic Emergency Stop (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."HYDR_PUMP_START_TC1" IS 'Hydraulic Pump Start (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."HYDR_PUMP_FAULT_TC1" IS 'Hydraulic Pump Fault (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."STOPPER_POS_SIGNAL_FAULT_TC1" IS 'Stopper Position Signal Fault (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."OIL_TEMP_MIN_TC1" IS 'Oil Temp Min (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."OIL_TEMP_MAX_TC1" IS 'Oil Temp Max (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."OIL_LEVEL_MIN_TC1" IS 'Oil Level Min (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."PRESSURE_FAULT_TC1" IS 'Pressure Fault (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."FILTER_CLOGGED_TC1" IS 'Filter Clogged (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."HYDR_PUMP_START_TC2" IS 'Hydraulic Pump Start (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."HYDR_PUMP_FAULT_TC2" IS 'Hydraulic Pump Fault (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."STOPPER_POS_SIGNAL_FAULT_TC2" IS 'Stopper Position Signal Fault (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."OIL_TEMP_MIN_TC2" IS 'Oil Temp Min (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."OIL_TEMP_MAX_TC2" IS 'Oil Temp Max (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."OIL_LEVEL_MIN_TC2" IS 'Oil Level Min (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."PRESSURE_FAULT_TC2" IS 'Pressure Fault (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."FILTER_CLOGGED_TC2" IS 'Filter Clogged (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."HYDR_STATUS" IS 'Hydrulic Status (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."ACOUSTIC_ALARM" IS 'Acoustic Alarm (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_MIN_ALARM" IS 'Minimum Alarm (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."LEVEL_MAX_ALARM" IS 'Maximum Alarm (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."FULL_CALIB_STATUS" IS 'Full Calibration (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."EMPTY_CALIB_STATUS" IS 'Empty Calibration (0 = False, 1 = True)';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."AIM_MOULD_LEVEL" IS 'MLC Aim Mold Level Str1 - L3 information';
   COMMENT ON COLUMN "PC_MOULD_CONTROL"."STOPPER_OPEN_POS" IS 'Unit [%] : Tundish stopper open position';
