--------------------------------------------------------
--  DDL for Table PC_PIECE
--------------------------------------------------------

  CREATE TABLE "PC_PIECE" 
   (	"ID" NUMBER, 
	"PIECE_ID" NUMBER, 
	"STRAND_NO" NUMBER, 
	"MARKING_NUMBER_SET" VARCHAR2(20 BYTE), 
	"MARKING_NUMBER_ACT" VARCHAR2(20 BYTE), 
	"S_HEAT_ID" NUMBER, 
	"CUT_TIME" DATE, 
	"PIECE_TYPE_ID" NUMBER, 
	"HOT_LEN" FLOAT(126), 
	"COLD_LEN" FLOAT(126), 
	"ORDERED_LEN" FLOAT(126), 
	"THICKNESS" NUMBER, 
	"HEAD_WIDTH" NUMBER, 
	"TAIL_WIDTH" NUMBER, 
	"PIECE_WEIGHT" NUMBER, 
	"HEAD_OF_PIECE" FLOAT(126), 
	"BNDR_POS" FLOAT(126), 
	"SAMPLE_LEN" FLOAT(126), 
	"SAMPLE_WEIGHT" NUMBER, 
	"PROD_ORDER_ID" VARCHAR2(20 BYTE), 
	"SLAB_ORDER_ID" NUMBER, 
	"STEEL_GRADE" VARCHAR2(20 BYTE), 
	"QUALITY_RES" NUMBER, 
	"ABN_COND1" NUMBER, 
	"ABN_COND2" NUMBER, 
	"DEFECT1" NUMBER, 
	"DEFECT2" NUMBER, 
	"BAUMAN_RES" NUMBER, 
	"SLAB_MARKED" NUMBER(1,0), 
	"SLAB_PUSHED" DATE, 
	"LAST_ONE" NUMBER(1,0), 
	"LAST_IN_STRAND" NUMBER(1,0), 
	"SHROUD" NUMBER(1,0), 
	"HEAD_SCRAP" NUMBER(1,0), 
	"END_SCRAP" NUMBER(1,0), 
	"CUT_LOSS" FLOAT(126), 
	"TZ_START" FLOAT(126), 
	"TZ_END" FLOAT(126), 
	"L3_SENT" NUMBER, 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;

   COMMENT ON COLUMN "PC_PIECE"."STRAND_NO" IS 'Strand no';
   COMMENT ON COLUMN "PC_PIECE"."MARKING_NUMBER_SET" IS 'Marking number set point L2';
   COMMENT ON COLUMN "PC_PIECE"."MARKING_NUMBER_ACT" IS 'Marking number actual value L1';
   COMMENT ON COLUMN "PC_PIECE"."S_HEAT_ID" IS 'heat identification';
   COMMENT ON COLUMN "PC_PIECE"."HOT_LEN" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_PIECE"."COLD_LEN" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_PIECE"."ORDERED_LEN" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_PIECE"."THICKNESS" IS 'Unit [mm] : ';
   COMMENT ON COLUMN "PC_PIECE"."HEAD_WIDTH" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_PIECE"."TAIL_WIDTH" IS 'Unit [mm] : ';
   COMMENT ON COLUMN "PC_PIECE"."PIECE_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PC_PIECE"."HEAD_OF_PIECE" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_PIECE"."BNDR_POS" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_PIECE"."SAMPLE_LEN" IS 'Unit [m] : ';
   COMMENT ON COLUMN "PC_PIECE"."SAMPLE_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PC_PIECE"."STEEL_GRADE" IS 'actual steel grade';
   COMMENT ON COLUMN "PC_PIECE"."QUALITY_RES" IS 'Bad: 0 = prime , 1 = quality problems, need to be checked, 2 = scrap- result of quality control model, operator confirms';
   COMMENT ON COLUMN "PC_PIECE"."SLAB_MARKED" IS 'Marked by operator: 0 = no , 1 = yes L2';
   COMMENT ON COLUMN "PC_PIECE"."SLAB_PUSHED" IS 'Slab pushed to central roller table L1';
   COMMENT ON COLUMN "PC_PIECE"."LAST_ONE" IS 'Last slab of heat: 0 = no , 1 = yes L2';
   COMMENT ON COLUMN "PC_PIECE"."LAST_IN_STRAND" IS 'Last Slab in strand: 0 = no , 1 = yes L2 ';
   COMMENT ON COLUMN "PC_PIECE"."SHROUD" IS 'Ladle shrouding: 0 = no , 1 = yes Manual entry';
   COMMENT ON COLUMN "PC_PIECE"."HEAD_SCRAP" IS 'Scrap on front: 0 = no , 1 = yes L2';
   COMMENT ON COLUMN "PC_PIECE"."END_SCRAP" IS 'Scrap at end of slab: 0 = no , 1 = yes L2';
   COMMENT ON COLUMN "PC_PIECE"."CUT_LOSS" IS 'Cut loss';
   COMMENT ON COLUMN "PC_PIECE"."L3_SENT" IS 'L3 sent flag';
