--------------------------------------------------------
--  DDL for Table PE_HEAT
--------------------------------------------------------

  CREATE TABLE "PE_HEAT" 
   (	"ID" NUMBER, 
	"S_HEAT_ID" NUMBER, 
	"C_HEAT_STATUS_ID" NUMBER, 
	"C_PLANT_UNIT_ID" NUMBER, 
	"CE_PRACTICE_ID" NUMBER, 
	"C_STEEL_GRADE_ID" NUMBER, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"C_PHASE_ID" NUMBER, 
	"NUM_OF_BASKETS" NUMBER, 
	"NUM_OF_HOT_METAL" NUMBER, 
	"STEEL_WEIGHT" NUMBER(8,0), 
	"SLAG_WEIGHT" NUMBER(8,0), 
	"HOT_HEEL_WEIGHT" NUMBER(8,0), 
	"STEEL_TEMPERATURE" NUMBER(4,0), 
	"START_TEMPERATURE" NUMBER(4,0), 
	"TAP_TEMPERATURE" NUMBER(4,0), 
	"POWER_ON_TIME" NUMBER(6,0), 
	"T1_TIME" NUMBER(6,0), 
	"ENERGY_TOTAL" NUMBER(12,1), 
	"SCRAP_WEIGHT" NUMBER(8,0), 
	"DRI_WEIGHT" NUMBER(8,0), 
	"LIME_WEIGHT" NUMBER(8,0), 
	"DOLO_WEIGHT" NUMBER(8,0), 
	"DRI_FEED_RATE" NUMBER(8,2), 
	"LIME_FEED_RATE" NUMBER(8,2), 
	"DOLO_FEED_RATE" NUMBER(8,2), 
	"C_CONTENT" NUMBER(3,0), 
	"O_CONTENT" NUMBER(4,0), 
	"OXYGEN_CONS" NUMBER(6,2), 
	"MIX_GAS_CONS" NUMBER(6,2), 
	"COKE_CONS" NUMBER(6,2), 
	"METHANE_CONS" NUMBER(6,2), 
	"NITROGEN_CONS" NUMBER(6,2), 
	"ACT_TAP_NO" NUMBER, 
	"TILTING_ANGLE" NUMBER, 
	"ROOF_POSITION" NUMBER, 
	"ELECTRODE_POSITION" NUMBER, 
	"TAP_START" DATE, 
	"TAP_END" DATE, 
	"TAPPING_TIME" NUMBER(6,0), 
	"C_EQUIPMENT_ID_LADLE" NUMBER, 
	"LADLE_WEIGHT" NUMBER(8,0), 
	"LADLE_TARE_WEIGHT" NUMBER(6,0), 
	"LADLE_STEEL_NET_WEIGHT" NUMBER(6,0), 
	"TAP_SLAG_WEIGHT" NUMBER(6,0), 
	"SLAG_PERCENTAGE" NUMBER(2,0), 
	"HOT_TAPPED" NUMBER(1,0), 
	"HOT_TAP_REASON" VARCHAR2(512 BYTE), 
	"VERIFIED" NUMBER(2,0) DEFAULT 0, 
	"VER_COMMENT" VARCHAR2(512 BYTE), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE), 
	"POWER_ON_TIME_SUM" NUMBER
   ) ;

   COMMENT ON COLUMN "PE_HEAT"."S_HEAT_ID" IS 'heat identification';
   COMMENT ON COLUMN "PE_HEAT"."C_HEAT_STATUS_ID" IS 'Heat status from C_HEAT_STATUS table';
   COMMENT ON COLUMN "PE_HEAT"."C_PLANT_UNIT_ID" IS 'Plant unit identification C_PLANT_UNIT table';
   COMMENT ON COLUMN "PE_HEAT"."CE_PRACTICE_ID" IS 'production practice identification';
   COMMENT ON COLUMN "PE_HEAT"."C_STEEL_GRADE_ID" IS 'actual steel grade - C_STEEL_GRADE';
   COMMENT ON COLUMN "PE_HEAT"."C_PHASE_ID" IS 'process phase identification - see tab. C_PHASE';
   COMMENT ON COLUMN "PE_HEAT"."NUM_OF_BASKETS" IS 'number of charged baskets';
   COMMENT ON COLUMN "PE_HEAT"."NUM_OF_HOT_METAL" IS 'number of charged hot metal';
   COMMENT ON COLUMN "PE_HEAT"."STEEL_WEIGHT" IS 'Unit [kg] : current steel weight in EAF';
   COMMENT ON COLUMN "PE_HEAT"."SLAG_WEIGHT" IS 'Unit [kg] : current slag weight in EAF';
   COMMENT ON COLUMN "PE_HEAT"."HOT_HEEL_WEIGHT" IS 'Unit [kg] : Start hot heel weight';
   COMMENT ON COLUMN "PE_HEAT"."STEEL_TEMPERATURE" IS 'Unit [°C] : current steel temperature at EAF end';
   COMMENT ON COLUMN "PE_HEAT"."START_TEMPERATURE" IS 'Unit [°C] : start temperature at EAF end';
   COMMENT ON COLUMN "PE_HEAT"."TAP_TEMPERATURE" IS 'Unit [C] : ';
   COMMENT ON COLUMN "PE_HEAT"."POWER_ON_TIME" IS 'Unit [min] : ';
   COMMENT ON COLUMN "PE_HEAT"."T1_TIME" IS 'Unit [min] : time from announce to first power on';
   COMMENT ON COLUMN "PE_HEAT"."ENERGY_TOTAL" IS 'Unit [kWh] : ';
   COMMENT ON COLUMN "PE_HEAT"."SCRAP_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PE_HEAT"."DRI_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PE_HEAT"."LIME_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PE_HEAT"."DOLO_WEIGHT" IS 'Unit [kg] : ';
   COMMENT ON COLUMN "PE_HEAT"."DRI_FEED_RATE" IS 'Unit [kg/min]';
   COMMENT ON COLUMN "PE_HEAT"."LIME_FEED_RATE" IS 'Unit [kg/min]';
   COMMENT ON COLUMN "PE_HEAT"."DOLO_FEED_RATE" IS 'Unit [kg/min]';
   COMMENT ON COLUMN "PE_HEAT"."C_CONTENT" IS 'Unit [%] : ';
   COMMENT ON COLUMN "PE_HEAT"."O_CONTENT" IS 'Unit [ppm] : Measured O content';
   COMMENT ON COLUMN "PE_HEAT"."OXYGEN_CONS" IS 'Unit [Nm3] : ';
   COMMENT ON COLUMN "PE_HEAT"."MIX_GAS_CONS" IS 'Unit [Nm3] : ';
   COMMENT ON COLUMN "PE_HEAT"."COKE_CONS" IS 'Unit [Nm3] : ';
   COMMENT ON COLUMN "PE_HEAT"."METHANE_CONS" IS 'Unit [Nm3] : ';
   COMMENT ON COLUMN "PE_HEAT"."NITROGEN_CONS" IS 'Unit [Nm3] : ';
   COMMENT ON COLUMN "PE_HEAT"."TAP_START" IS 'Tapping start time';
   COMMENT ON COLUMN "PE_HEAT"."TAP_END" IS 'Tapping end time';
   COMMENT ON COLUMN "PE_HEAT"."TAPPING_TIME" IS 'Unit [min] : time from tapping start to tapping end';
   COMMENT ON COLUMN "PE_HEAT"."LADLE_WEIGHT" IS 'Unit [kg] : current ladle weight';
   COMMENT ON COLUMN "PE_HEAT"."LADLE_TARE_WEIGHT" IS 'Ladle tare weight';
   COMMENT ON COLUMN "PE_HEAT"."LADLE_STEEL_NET_WEIGHT" IS 'Ladle steel weight';
   COMMENT ON COLUMN "PE_HEAT"."TAP_SLAG_WEIGHT" IS 'Slag weight';
   COMMENT ON COLUMN "PE_HEAT"."SLAG_PERCENTAGE" IS 'Slag percentage';
   COMMENT ON COLUMN "PE_HEAT"."HOT_TAPPED" IS '0=no, 1=yes';
   COMMENT ON COLUMN "PE_HEAT"."VERIFIED" IS 'Flag verified by OP 0=NO, 1=YES';
   COMMENT ON COLUMN "PE_HEAT"."VER_COMMENT" IS 'Verification comment';
   COMMENT ON COLUMN "PE_HEAT"."POWER_ON_TIME_SUM" IS 'Total time when power was on.. In seconds';
