--------------------------------------------------------
--  DDL for Table PE_HOT_METAL
--------------------------------------------------------

  CREATE TABLE "PE_HOT_METAL" 
   (	"ID" NUMBER, 
	"C_EQUIPMENT_ID_LADLE" NUMBER, 
	"S_HEAT_ID" NUMBER, 
	"TAP_ID" VARCHAR2(20 BYTE), 
	"MAT_WEIGHT" NUMBER(8,0), 
	"TEMPERATURE" NUMBER(4,0), 
	"DISCHARGED_DATE" DATE, 
	"SI_CONTENT" NUMBER, 
	"CONTI_CHARGE" NUMBER, 
	"TORPEDO_NO" NUMBER, 
	"ARRIVAL_TIME" DATE, 
	"DEPARTURE_TIME" DATE, 
	"INIT_WEIGHT" NUMBER, 
	"FINAL_WEIGHT" NUMBER, 
	"BF_WEIGHT" NUMBER, 
	"BF_TEMP" NUMBER, 
	"TORPEDO_TEMP" NUMBER, 
	"BF_SI_CONTENT" NUMBER, 
	"LOW_TEMP_REASON" VARCHAR2(50 BYTE), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;
