--------------------------------------------------------
--  DDL for Table PL_HEAT_REP_ACTIVITY
--------------------------------------------------------

  CREATE TABLE "PL_HEAT_REP_ACTIVITY" 
   (	"ID" NUMBER, 
	"S_HEAT_ID" NUMBER, 
	"ACTIVITY_NAME" VARCHAR2(256 BYTE), 
	"ACTIVITY_TIME" VARCHAR2(256 BYTE), 
	"TEMPERATURE" NUMBER, 
	"POWER_CONS" NUMBER, 
	"LIME" NUMBER, 
	"DOLO_LIME" NUMBER, 
	"SYN_SLAG" NUMBER, 
	"AL" NUMBER, 
	"SLMN" NUMBER, 
	"FEMNHC" NUMBER, 
	"FESI" NUMBER, 
	"FESIFINE" NUMBER, 
	"FEMNLC" NUMBER, 
	"FEMNMC" NUMBER, 
	"FECRLC" NUMBER, 
	"FECRHC" NUMBER, 
	"FECRLT" NUMBER, 
	"MNMETAL" NUMBER, 
	"FEMO" NUMBER, 
	"FEV" NUMBER, 
	"FENB" NUMBER, 
	"FETI" NUMBER, 
	"NICKEL" NUMBER, 
	"ALWIRE" NUMBER, 
	"FEB" NUMBER, 
	"CPC" NUMBER, 
	"RADEX" NUMBER, 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;
