--------------------------------------------------------
--  DDL for Table PL_HEAT
--------------------------------------------------------

  CREATE TABLE "PL_HEAT" 
   (	"ID" NUMBER, 
	"S_HEAT_ID" NUMBER, 
	"TREAT_NO" NUMBER DEFAULT 0, 
	"C_HEAT_STATUS_ID" NUMBER, 
	"C_PLANT_UNIT_ID" NUMBER, 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"CL_PRACTICE_ID" NUMBER, 
	"AIM_TEMP" NUMBER(4,0), 
	"HYDROGEN_CRITICAL" NUMBER, 
	"PHASE_SEQ_NO_CURR" NUMBER, 
	"C_PHASE_ID" NUMBER, 
	"C_STEEL_GRADE_ID" NUMBER, 
	"C_EQUIPMENT_ID_LADLE" NUMBER, 
	"LADLE_POS" VARCHAR2(20 BYTE), 
	"POWER_ON_TIME" NUMBER(6,0), 
	"ENERGY_TOTAL" NUMBER(12,1), 
	"TRANSPORT_TIME" NUMBER(6,0), 
	"CAR_MOVE" NUMBER(6,0), 
	"ARRIVAL" DATE, 
	"ARRIVAL_TEMP" NUMBER(4,0), 
	"DEPARTURE" DATE, 
	"DEPARTURE_TEMP" NUMBER(4,0), 
	"RETURN_HEAT_ID" VARCHAR2(20 BYTE), 
	"RETURN_WEIGHT" NUMBER(8,0), 
	"STEEL_WEIGHT" NUMBER(8,0), 
	"SLAG_WEIGHT" NUMBER(8,0), 
	"STEEL_TEMPERATURE" NUMBER(4,0), 
	"H_MEAS_REQUESTED" NUMBER, 
	"AIM_TIME" DATE, 
	"AR_CONS" NUMBER(12,4), 
	"N2_CONS" NUMBER(12,4), 
	"VERIFIED" NUMBER(2,0) DEFAULT 0, 
	"VER_COMMENT" VARCHAR2(512 BYTE), 
	"LADLE_STATE" VARCHAR2(1 BYTE), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE), 
	"ACT_TAP_NO" NUMBER, 
	"ACT_CURVE_NO" NUMBER, 
	"AR_FLOW" NUMBER, 
	"AR_CONS2" NUMBER, 
	"AR_FLOW2" NUMBER, 
	"FIRST_POWER_ON_TIME" DATE
   ) ;

   COMMENT ON COLUMN "PL_HEAT"."S_HEAT_ID" IS 'heat identification';
   COMMENT ON COLUMN "PL_HEAT"."TREAT_NO" IS 'Treatment number';
   COMMENT ON COLUMN "PL_HEAT"."C_HEAT_STATUS_ID" IS '';
   COMMENT ON COLUMN "PL_HEAT"."CL_PRACTICE_ID" IS 'production practice identification';
   COMMENT ON COLUMN "PL_HEAT"."AIM_TEMP" IS 'Manuel entry of AiM temperature at LF';
   COMMENT ON COLUMN "PL_HEAT"."HYDROGEN_CRITICAL" IS 'Hydrogen critical heat, HYDRIS should be taken';
   COMMENT ON COLUMN "PL_HEAT"."PHASE_SEQ_NO_CURR" IS 'sequence number of the current process phase';
   COMMENT ON COLUMN "PL_HEAT"."C_PHASE_ID" IS 'process phase identification - see tab. C_PHASE';
   COMMENT ON COLUMN "PL_HEAT"."C_STEEL_GRADE_ID" IS 'actual steel grade';
   COMMENT ON COLUMN "PL_HEAT"."C_EQUIPMENT_ID_LADLE" IS 'Ladle reference to C_EQUIPMENT table';
   COMMENT ON COLUMN "PL_HEAT"."LADLE_POS" IS 'current position of ladle with the heat';
   COMMENT ON COLUMN "PL_HEAT"."POWER_ON_TIME" IS 'Unit [min] : ';
   COMMENT ON COLUMN "PL_HEAT"."ENERGY_TOTAL" IS 'Unit [kWh] : ';
   COMMENT ON COLUMN "PL_HEAT"."TRANSPORT_TIME" IS 'Unit [min] : ';
   COMMENT ON COLUMN "PL_HEAT"."CAR_MOVE" IS 'Unit [min] : ';
   COMMENT ON COLUMN "PL_HEAT"."ARRIVAL_TEMP" IS 'Unit [°C] : ';
   COMMENT ON COLUMN "PL_HEAT"."DEPARTURE_TEMP" IS 'Unit [°C] : ';
   COMMENT ON COLUMN "PL_HEAT"."RETURN_HEAT_ID" IS 'Returned heat from Caster and added to the ladle';
   COMMENT ON COLUMN "PL_HEAT"."RETURN_WEIGHT" IS 'Returned steel weight';
   COMMENT ON COLUMN "PL_HEAT"."STEEL_WEIGHT" IS 'Unit [kg] : steel weight in ladle';
   COMMENT ON COLUMN "PL_HEAT"."SLAG_WEIGHT" IS 'Unit [kg] : slag weight in ladle';
   COMMENT ON COLUMN "PL_HEAT"."STEEL_TEMPERATURE" IS 'Unit [°C] : steel temperature in ladle';
   COMMENT ON COLUMN "PL_HEAT"."H_MEAS_REQUESTED" IS 'hydris measurement is needed';
   COMMENT ON COLUMN "PL_HEAT"."AIM_TIME" IS 'aim time';
   COMMENT ON COLUMN "PL_HEAT"."VERIFIED" IS 'Flag verified by OP 0=NO, 1=YES';
   COMMENT ON COLUMN "PL_HEAT"."VER_COMMENT" IS 'Verification comment';
   COMMENT ON COLUMN "PL_HEAT"."LADLE_STATE" IS 'Ladle state - c,w,h = cold,warm,hot';
