--------------------------------------------------------
--  DDL for Table PV_HEAT_PHASES
--------------------------------------------------------

  CREATE TABLE "PV_HEAT_PHASES" 
   (	"ID" NUMBER, 
	"PV_HEAT_ID" NUMBER, 
	"C_PHASE_ID" NUMBER, 
	"PRESSURE_START" NUMBER, 
	"PRESSURE_END" NUMBER, 
	"PHASE_START" DATE, 
	"PHASE_DURATION" NUMBER, 
	"PUMP_START" DATE, 
	"PUMP_DURATION" NUMBER, 
	"DEGASSING_START" DATE, 
	"DEGASSING_DURATION" NUMBER, 
	"AR_CONS" NUMBER(12,4), 
	"N2_CONS" NUMBER(12,4), 
	"CREATED" DATE, 
	"MODIFIED" DATE, 
	"MOP" VARCHAR2(120 BYTE)
   ) ;
